/**
 * LeanOS Deal Pipeline Orchestrator
 * 딜→견적서→계약서→세금계산서→입금스케줄 자동 파이프라인
 *
 * Flow:
 *   1. 딜에서 "견적서 생성" → Draft (딜 데이터 자동 채움)
 *   2. 견적서 승인 → 계약서 자동 생성
 *   3. 계약서 승인 → 세금계산서 자동 발행 + 매출스케줄 자동 생성 (선금/잔금)
 *   4. 입금 확인 → 3-Way 매칭 + 딜 상태 업데이트
 */

import { supabase } from './supabase';
import { createTaxInvoice } from './tax-invoice';
import { createQueueEntry } from './payment-queue';
import { dispatchBusinessEvent, type BusinessEventType } from './business-events';
import type { Json } from '@/types/database';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const db = supabase as any;

// ── Types ──

export type DocChainType = 'invoice' | 'contract' | 'quote';

export interface PipelineStage {
  stage: 'quote' | 'contract' | 'tax_invoice' | 'payment_schedule' | 'payment_received';
  status: 'pending' | 'active' | 'completed' | 'skipped';
  documentId?: string;
  completedAt?: string;
}

// ── 1. Create document from deal data (auto-fill) ──

export async function createDocumentFromDeal(params: {
  companyId: string;
  dealId: string;
  docType: DocChainType;
  createdBy: string;
}): Promise<string> {
  const { companyId, dealId, docType, createdBy } = params;

  // Fetch deal + partner info
  const { data: deal } = await db
    .from('deals')
    .select('*, partners(name, business_number, contact_email, contact_phone)')
    .eq('id', dealId)
    .single();

  if (!deal) throw new Error('딜을 찾을 수 없습니다');

  const partnerName = deal.partners?.name || deal.counterparty || '';
  const partnerBizNo = deal.partners?.business_number || '';
  const contractTotal = Number(deal.contract_total || 0);

  // Build content JSON based on doc type
  const typeLabels: Record<DocChainType, string> = {
    invoice: '견적서',
    contract: '계약서',
    quote: '제안서',
  };

  const contentJson: Record<string, unknown> = {
    type: docType,
    dealId,
    dealName: deal.name,
    partnerName,
    partnerBizNo,
    partnerEmail: deal.partners?.contact_email || '',
    partnerPhone: deal.partners?.contact_phone || '',
    contractTotal,
    supplyAmount: contractTotal,
    taxAmount: Math.round(contractTotal * 0.1),
    totalWithTax: Math.round(contractTotal * 1.1),
    sections: [],
    metadata: {
      autoGenerated: true,
      sourceDocType: docType,
      generatedAt: new Date().toISOString(),
    },
  };

  // Add contract-specific fields
  if (docType === 'contract') {
    Object.assign(contentJson, {
      contractStartDate: new Date().toISOString().split('T')[0],
      contractEndDate: '',
      paymentTerms: '계약금 30% (계약 후 7일 이내), 잔금 70% (납품 완료 후 14일 이내)',
    });
  }

  // Add quote-specific fields
  if (docType === 'invoice') {
    Object.assign(contentJson, {
      validUntil: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      items: deal.items || [],
    });
  }

  const name = `${deal.name} - ${typeLabels[docType]}`;

  const { data: doc, error } = await supabase
    .from('documents')
    .insert({
      company_id: companyId,
      deal_id: dealId,
      name,
      status: 'draft',
      content_json: contentJson as unknown as Json,
      version: 1,
      created_by: createdBy,
    })
    .select()
    .single();

  if (error) throw error;
  return doc.id;
}

// ── 2. On document approved — trigger pipeline ──

export async function onDocumentApproved(params: {
  documentId: string;
  companyId: string;
  approverId: string;
}): Promise<{ nextAction?: string; createdDocId?: string; createdInvoiceId?: string }> {
  const { documentId, companyId, approverId } = params;

  // Fetch the document
  const { data: doc } = await supabase
    .from('documents')
    .select('id, name, deal_id, content_json')
    .eq('id', documentId)
    .single();

  if (!doc || !doc.deal_id) return {};

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const content = doc.content_json as any;
  const docType = content?.type as string;

  // CASE A: 견적서(invoice/quote) 승인 → 계약서 자동 생성
  if (docType === 'invoice' || docType === 'quote') {
    const contractDocId = await createDocumentFromDeal({
      companyId,
      dealId: doc.deal_id,
      docType: 'contract',
      createdBy: approverId,
    });

    // Dispatch event
    await dispatchBusinessEvent({
      dealId: doc.deal_id,
      eventType: 'document_approved' as BusinessEventType,
      userId: approverId,
      referenceId: contractDocId,
      referenceTable: 'documents',
      summary: { title: `계약서 자동 생성됨 (견적서 승인 기반)` },
    });

    return { nextAction: 'contract_created', createdDocId: contractDocId };
  }

  // CASE B: 계약서 승인 → 세금계산서 + 매출스케줄 자동 생성
  if (docType === 'contract') {
    const result = await onContractApproved({
      dealId: doc.deal_id,
      companyId,
      userId: approverId,
      contractTotal: Number(content?.contractTotal || content?.supplyAmount || 0),
      partnerName: content?.partnerName || '',
      partnerBizNo: content?.partnerBizNo || '',
    });

    return {
      nextAction: 'tax_invoice_and_schedule_created',
      createdInvoiceId: result.invoiceId || undefined,
    };
  }

  return {};
}

// ── 3. On contract approved — issue tax invoice + payment schedule ──

async function onContractApproved(params: {
  dealId: string;
  companyId: string;
  userId: string;
  contractTotal: number;
  partnerName: string;
  partnerBizNo: string;
}) {
  const { dealId, companyId, userId, contractTotal, partnerName, partnerBizNo } = params;
  let invoiceId: string | null = null;

  // 3a. 세금계산서 자동 발행
  if (contractTotal > 0) {
    const invoice = await createTaxInvoice({
      companyId,
      dealId,
      type: 'sales',
      counterpartyName: partnerName,
      counterpartyBizno: partnerBizNo,
      supplyAmount: contractTotal,
      issueDate: new Date().toISOString().split('T')[0],
    });
    invoiceId = invoice?.id || null;

    if (invoiceId) {
      await dispatchBusinessEvent({
        dealId,
        eventType: 'invoice_issued' as BusinessEventType,
        userId,
        referenceId: invoiceId,
        referenceTable: 'tax_invoices',
        summary: { amount: Math.round(contractTotal * 1.1), title: '세금계산서 자동 발행' },
      });
    }
  }

  // 3b. 매출 스케줄 자동 생성 (선금 30% + 잔금 70%)
  await createPaymentScheduleFromContract({
    dealId,
    companyId,
    contractTotal,
    userId,
  });

  return { invoiceId };
}

// ── 4. Create payment schedule (선금/잔금) ──

async function createPaymentScheduleFromContract(params: {
  dealId: string;
  companyId: string;
  contractTotal: number;
  userId: string;
}) {
  const { dealId, companyId, contractTotal, userId } = params;
  if (contractTotal <= 0) return;

  const advanceAmount = Math.round(contractTotal * 0.3);
  const balanceAmount = contractTotal - advanceAmount;
  const now = new Date();
  const advanceDue = new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000); // +7 days
  const balanceDue = new Date(now.getTime() + 60 * 24 * 60 * 60 * 1000); // +60 days (납품 후)

  // Insert revenue schedule entries
  const scheduleEntries = [
    {
      deal_id: dealId,
      label: '선금 (30%)',
      amount: advanceAmount,
      due_date: advanceDue.toISOString().split('T')[0],
      status: 'expected',
    },
    {
      deal_id: dealId,
      label: '잔금 (70%)',
      amount: balanceAmount,
      due_date: balanceDue.toISOString().split('T')[0],
      status: 'expected',
    },
  ];

  await db.from('deal_revenue_schedule').insert(scheduleEntries);

  // Also create payment queue entry for advance payment notification
  await createQueueEntry({
    companyId,
    amount: advanceAmount,
    description: `선금 30% 입금 예정 (D+7)`,
    costType: 'revenue',
  });

  await dispatchBusinessEvent({
    dealId,
    eventType: 'milestone_completed' as BusinessEventType,
    userId,
    referenceId: dealId,
    referenceTable: 'deals',
    summary: {
      title: `매출 스케줄 생성: 선금 ${advanceAmount.toLocaleString()}원 / 잔금 ${balanceAmount.toLocaleString()}원`,
    },
  });
}

// ── 5. On revenue received — 3-way match + deal update ──

export async function onRevenueReceived(params: {
  dealId: string;
  companyId: string;
  amount: number;
  userId: string;
  revenueScheduleId?: string;
}) {
  const { dealId, companyId, amount, userId, revenueScheduleId } = params;

  // Mark revenue schedule as received
  if (revenueScheduleId) {
    await db
      .from('deal_revenue_schedule')
      .update({
        status: 'received',
        received_date: new Date().toISOString().split('T')[0],
      })
      .eq('id', revenueScheduleId);
  }

  // Check if all revenue received
  const { data: schedules } = await db
    .from('deal_revenue_schedule')
    .select('id, amount, status')
    .eq('deal_id', dealId);

  const allReceived = (schedules || []).every((s: { status: string }) => s.status === 'received');
  const totalExpected = (schedules || []).reduce(
    (sum: number, s: { amount: number }) => sum + Number(s.amount || 0), 0
  );
  const totalReceived = (schedules || [])
    .filter((s: { status: string }) => s.status === 'received')
    .reduce((sum: number, s: { amount: number }) => sum + Number(s.amount || 0), 0);

  // Update deal status if fully paid
  if (allReceived && totalReceived >= totalExpected) {
    await db
      .from('deals')
      .update({ status: 'completed', last_activity_at: new Date().toISOString() })
      .eq('id', dealId);

    await dispatchBusinessEvent({
      dealId,
      eventType: 'deal_status_changed' as BusinessEventType,
      userId,
      referenceId: dealId,
      referenceTable: 'deals',
      summary: { from: 'active', to: 'completed', reason: '전액 입금 완료' },
    });
  }

  // Dispatch payment received event
  await dispatchBusinessEvent({
    dealId,
    eventType: 'payment_received' as BusinessEventType,
    userId,
    referenceId: revenueScheduleId || dealId,
    referenceTable: revenueScheduleId ? 'deal_revenue_schedule' : 'deals',
    summary: {
      amount,
      totalReceived,
      totalExpected,
      progress: totalExpected > 0 ? Math.round((totalReceived / totalExpected) * 100) : 0,
    },
  });
}

// ── 6. Get pipeline status for a deal ──

export async function getDealPipelineStatus(dealId: string): Promise<PipelineStage[]> {
  // Get all documents linked to this deal
  const { data: docs } = await supabase
    .from('documents')
    .select('id, name, status, content_json, created_at')
    .eq('deal_id', dealId)
    .order('created_at', { ascending: true });

  // Get tax invoices for this deal
  const { data: invoices } = await supabase
    .from('tax_invoices')
    .select('id, status, total_amount, issue_date')
    .eq('deal_id', dealId)
    .neq('status', 'void');

  // Get revenue schedule
  const { data: schedules } = await db
    .from('deal_revenue_schedule')
    .select('id, status, amount')
    .eq('deal_id', dealId);

  const stages: PipelineStage[] = [];

  // Stage 1: Quote/Invoice document
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const quoteDoc = (docs || []).find((d: any) => {
    const ct = d.content_json as any;
    return ct?.type === 'invoice' || ct?.type === 'quote';
  });
  stages.push({
    stage: 'quote',
    status: !quoteDoc ? 'pending' : quoteDoc.status === 'approved' || quoteDoc.status === 'locked' ? 'completed' : 'active',
    documentId: quoteDoc?.id,
    completedAt: quoteDoc?.status === 'approved' ? (quoteDoc.created_at ?? undefined) : undefined,
  });

  // Stage 2: Contract document
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const contractDoc = (docs || []).find((d: any) => {
    const ct = d.content_json as any;
    return ct?.type === 'contract';
  });
  stages.push({
    stage: 'contract',
    status: !contractDoc ? 'pending' : contractDoc.status === 'approved' || contractDoc.status === 'locked' ? 'completed' : 'active',
    documentId: contractDoc?.id,
    completedAt: contractDoc?.status === 'approved' ? (contractDoc.created_at ?? undefined) : undefined,
  });

  // Stage 3: Tax invoice
  const hasInvoice = (invoices || []).length > 0;
  stages.push({
    stage: 'tax_invoice',
    status: !hasInvoice ? 'pending' : 'completed',
    documentId: invoices?.[0]?.id,
  });

  // Stage 4: Payment schedule created
  const hasSchedule = (schedules || []).length > 0;
  stages.push({
    stage: 'payment_schedule',
    status: !hasSchedule ? 'pending' : 'completed',
  });

  // Stage 5: Payment received
  const allPaid = hasSchedule && (schedules || []).every((s: { status: string }) => s.status === 'received');
  stages.push({
    stage: 'payment_received',
    status: allPaid ? 'completed' : hasSchedule ? 'active' : 'pending',
  });

  return stages;
}
