/**
 * OwnerView Deal Pipeline Orchestrator
 * 딜→견적서→계약서→세금계산서→입금스케줄 자동 파이프라인
 *
 * Flow:
 *   1. 딜에서 "견적서 생성" → Draft (딜 데이터 자동 채움)
 *   2. 견적서 승인 → 계약서 자동 생성
 *   3. 계약서 승인 → 세금계산서 자동 발행 + 매출스케줄 자동 생성 (선금/잔금)
 *   4. 입금 확인 → 3-Way 매칭 + 딜 상태 업데이트
 */

import { supabase } from './supabase';
import { createTaxInvoice, markInvoiceMatched, issueTaxInvoice } from './tax-invoice';
import { createQueueEntry } from './payment-queue';
import { dispatchBusinessEvent, type BusinessEventType } from './business-events';
import { generateContractPDF } from './document-generator';
import { createSignatureRequest, sendSignatureEmail, applyCompanySeal } from './signatures';
import type { Json } from '@/types/models';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const db = supabase as any;

// ── Types ──

export type DocChainType = 'invoice' | 'contract' | 'quote';

export interface PipelineStage {
  stage: 'quote' | 'contract' | 'tax_invoice' | 'payment_schedule' | 'payment_received';
  status: 'pending' | 'active' | 'completed' | 'skipped';
  documentId?: string;
  completedAt?: string;
}

// ── 1. Create document from deal data (auto-fill) ──

export async function createDocumentFromDeal(params: {
  companyId: string;
  dealId: string;
  docType: DocChainType;
  createdBy: string;
  items?: Array<{ name: string; quantity: number; unitPrice: number; supplyAmount: number; taxAmount: number; totalAmount: number; note?: string }>;
  paymentRatio?: { advance: number; balance: number };
}): Promise<string> {
  const { companyId, dealId, docType, createdBy, items: passedItems, paymentRatio } = params;

  // Fetch deal + partner info
  const { data: deal, error: dealError } = await db
    .from('deals')
    .select('*, partners!deals_partner_id_fkey(name, business_number, contact_email, contact_phone)')
    .eq('id', dealId)
    .eq('company_id', companyId)
    .single();

  if (dealError || !deal) throw new Error(`딜을 찾을 수 없습니다 (id: ${dealId}, error: ${dealError?.message || 'no data'})`);

  const partnerName = deal.partners?.name || deal.counterparty || '';
  const partnerBizNo = deal.partners?.business_number || '';
  const contractTotal = Number(deal.contract_total || 0);

  // Fetch company info for documents
  const { data: company } = await db.from('companies').select('name, business_number, representative, address').eq('id', companyId).single();
  const companyName = company?.name || '';
  const companyBizNo = company?.business_number || '';
  const companyRep = company?.representative || '';
  const companyAddr = company?.address || '';

  // Build content JSON based on doc type
  const typeLabels: Record<DocChainType, string> = {
    invoice: '견적서',
    contract: '계약서',
    quote: '제안서',
  };

  const contentJson: Record<string, unknown> = {
    type: docType,
    dealId,
    dealName: deal.name,
    partnerName,
    partnerBizNo,
    partnerEmail: deal.partners?.contact_email || '',
    partnerPhone: deal.partners?.contact_phone || '',
    contractTotal,
    supplyAmount: contractTotal,
    taxAmount: Math.round(contractTotal * 0.1),
    totalWithTax: Math.round(contractTotal * 1.1),
    sections: [],
    metadata: {
      autoGenerated: true,
      sourceDocType: docType,
      generatedAt: new Date().toISOString(),
    },
  };

  // Add contract-specific fields with structured paymentSchedule
  if (docType === 'contract') {
    // Inherit items from quote if available (견적→계약 승계)
    const sourceQuote = await (async () => {
      const { data: quoteDocs } = await db
        .from('documents')
        .select('content_json')
        .eq('deal_id', dealId)
        .order('created_at', { ascending: false });
      return (quoteDocs || []).find((d: any) => {
        const ct = d.content_json as any;
        return ct?.type === 'invoice' || ct?.type === 'quote';
      });
    })();
    const quoteContent = sourceQuote?.content_json as any;
    const inheritedItems = (quoteContent?.items && Array.isArray(quoteContent.items) && quoteContent.items.length > 0)
      ? quoteContent.items
      : [{
          name: deal.name || '',
          quantity: 1,
          unitPrice: contractTotal,
          supplyAmount: contractTotal,
          taxAmount: Math.round(contractTotal * 0.1),
          totalAmount: Math.round(contractTotal * 1.1),
          note: '',
        }];

    // Use custom payment ratio from quote content or passed params, fallback to 30/70
    const advanceRatio = quoteContent?.paymentRatio?.advance ?? paymentRatio?.advance ?? 30;
    const balanceRatio = quoteContent?.paymentRatio?.balance ?? paymentRatio?.balance ?? 70;

    Object.assign(contentJson, {
      contractStartDate: new Date().toISOString().split('T')[0],
      contractEndDate: '',
      paymentTerms: `계약금 ${advanceRatio}% (계약 후 7일 이내), 잔금 ${balanceRatio}% (납품 완료 후 14일 이내)`,
      paymentSchedule: [
        { label: '선금', ratio: advanceRatio, amount: Math.round(contractTotal * advanceRatio / 100), condition: '계약 후 7일 이내' },
        { label: '잔금', ratio: balanceRatio, amount: contractTotal - Math.round(contractTotal * advanceRatio / 100), condition: '납품 완료 후 14일 이내' },
      ],
      paymentRatio: { advance: advanceRatio, balance: balanceRatio },
      items: inheritedItems,
    });
  }

  // Add quote-specific fields with structured items
  if (docType === 'invoice') {
    const items = (passedItems && passedItems.length > 0)
      ? passedItems
      : (deal.items && Array.isArray(deal.items) && deal.items.length > 0)
        ? deal.items
        : [{
            name: deal.name || '',
            quantity: 1,
            unitPrice: contractTotal,
            supplyAmount: contractTotal,
            taxAmount: Math.round(contractTotal * 0.1),
            totalAmount: Math.round(contractTotal * 1.1),
            note: '',
          }];
    Object.assign(contentJson, {
      validUntil: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      items,
      ...(paymentRatio ? { paymentRatio } : {}),
    });
  }

  const name = `${deal.name} - ${typeLabels[docType]}`;

  // Generate human-readable body text
  const fmt = (n: number) => n.toLocaleString('ko-KR');
  const supplyAmt = contractTotal;
  const taxAmt = Math.round(contractTotal * 0.1);
  const totalAmt = supplyAmt + taxAmt;
  const today = new Date().toISOString().split('T')[0];
  const cj = contentJson as any;
  const itemsArr: any[] = cj.items || [];

  function buildItemsTable(items: any[]) {
    let t = '\n┌──────┬──────────────────────┬──────────┬──────────┬──────────────┬────────────────┐\n';
    t += '│  No  │ 품명                 │ 수량     │ 단가     │ 공급가액     │ 비고           │\n';
    t += '├──────┼──────────────────────┼──────────┼──────────┼──────────────┼────────────────┤\n';
    items.forEach((it: any, idx: number) => {
      const n = String(idx + 1).padStart(4);
      const nm = (it.name || '').slice(0, 18).padEnd(18);
      const q = String(it.quantity || 1).padStart(6);
      const u = fmt(Number(it.unitPrice || 0)).padStart(8);
      const a = fmt(Number(it.supplyAmount || it.amount || 0)).padStart(12);
      const note = (it.note || '').slice(0, 12).padEnd(12);
      t += `│ ${n} │ ${nm} │ ${q} │ ${u} │ ${a} │ ${note} │\n`;
    });
    t += '└──────┴──────────────────────┴──────────┴──────────┴──────────────┴────────────────┘\n';
    return t;
  }

  if (docType === 'invoice') {
    const validUntil = cj.validUntil || '';
    contentJson.body = `견 적 서

수 신: ${partnerName} 귀하
발 신: ${companyName}
견적일자: ${today}

아래와 같이 견적합니다.
${buildItemsTable(itemsArr)}
  공급가액:  ₩${fmt(supplyAmt)}
  부가세(10%): ₩${fmt(taxAmt)}
  ─────────────────────
  합계금액:  ₩${fmt(totalAmt)} (VAT 포함)

유효기간: ${validUntil}까지

[결제조건]
${cj.paymentRatio ? `선금 ${cj.paymentRatio.advance}% / 잔금 ${cj.paymentRatio.balance}%` : '협의'}

${companyName}
대표이사 ${companyRep} (직인)`;
  }

  if (docType === 'contract') {
    const schedule = cj.paymentSchedule || [];
    const scheduleText = schedule.map((s: any) => `  - ${s.label} (${s.ratio}%): ₩${fmt(s.amount)} — ${s.condition}`).join('\n');
    contentJson.body = `표 준 용 역 계 약 서

계약일자: ${today}

"갑" ${companyName} (사업자등록번호: ${companyBizNo})
     대표이사: ${companyRep}
     주소: ${companyAddr}

"을" ${partnerName} (사업자등록번호: ${partnerBizNo})


제1조 (목적)
본 계약은 "${deal.name}"에 관하여 갑과 을 사이의 권리·의무를 규정함을 목적으로 한다.

제2조 (용역의 범위)
을은 갑이 의뢰한 아래 용역을 성실히 수행한다.
${buildItemsTable(itemsArr)}

제3조 (계약금액 및 부가가치세)
  공급가액:  ₩${fmt(supplyAmt)}
  부가가치세(10%): ₩${fmt(taxAmt)}
  ─────────────────────
  합계금액:  ₩${fmt(totalAmt)} (VAT 포함)

제4조 (대금지급)
${scheduleText || cj.paymentTerms || '별도 협의'}

제5조 (계약기간)
${cj.contractStartDate || today} ~ ${cj.contractEndDate || '프로젝트 완료 시'}

제6조 (납품 및 검수)
을은 용역 완료 후 결과물을 갑에게 납품하고, 갑은 납품일로부터 7영업일 이내에 검수를 완료한다.
검수 결과 하자가 발견된 경우 을은 갑의 요청에 따라 무상으로 보완한다.

제7조 (지식재산권)
본 계약에 의해 수행된 용역의 결과물에 대한 저작재산권 및 소유권은 대금 완납 시 갑에게 귀속된다.

제8조 (비밀유지)
계약 당사자는 본 계약의 이행과정에서 취득한 상대방의 기밀정보를 제3자에게 누설하지 아니하며,
계약 종료 후에도 2년간 비밀유지 의무를 부담한다.

제9조 (손해배상)
계약 당사자가 본 계약을 위반하여 상대방에게 손해를 끼친 경우 그 손해를 배상한다.

제10조 (계약해제 및 해지)
1. 상대방이 본 계약상의 의무를 이행하지 않을 때 서면으로 최고한 후 7일 이내에 이행하지 않으면 계약을 해제·해지할 수 있다.
2. 갑의 사정으로 계약을 해지하는 경우 기 수행된 부분에 대해서는 정산하여 지급한다.

제11조 (불가항력)
천재지변, 전쟁 등 불가항력적인 사유로 계약을 이행할 수 없는 경우 그 책임을 면한다.

제12조 (분쟁해결)
본 계약에 관한 분쟁은 갑의 소재지 관할법원을 제1심 법원으로 한다.

본 계약의 성립을 증명하기 위하여 계약서 2통을 작성하고,
갑·을이 각각 서명 날인한 후 각 1통씩 보관한다.

${today}

"갑" ${companyName}  대표이사 ${companyRep} (인)
"을" ${partnerName}  대표이사 ______________ (인)`;
  }

  const { data: doc, error } = await db
    .from('documents')
    .insert({
      company_id: companyId,
      deal_id: dealId,
      name,
      status: 'draft',
      content_json: contentJson,
      version: 1,
      created_by: createdBy,
    })
    .select()
    .single();

  if (error) throw error;
  return doc.id;
}

// ── 2. On document approved — trigger pipeline ──

export async function onDocumentApproved(params: {
  documentId: string;
  companyId: string;
  approverId: string;
}): Promise<{ nextAction?: string; createdDocId?: string; createdInvoiceId?: string }> {
  const { documentId, companyId, approverId } = params;

  // Fetch the document
  const { data: doc } = await supabase
    .from('documents')
    .select('id, name, deal_id, content_json')
    .eq('id', documentId)
    .single();

  if (!doc || !doc.deal_id) return {};

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const content = doc.content_json as any;
  const docType = content?.type as string;

  // CASE A: 견적서(invoice/quote) 승인 → 계약서 자동 생성
  if (docType === 'invoice' || docType === 'quote') {
    const contractDocId = await createDocumentFromDeal({
      companyId,
      dealId: doc.deal_id,
      docType: 'contract',
      createdBy: approverId,
    });

    // Dispatch event
    await dispatchBusinessEvent({
      dealId: doc.deal_id,
      eventType: 'document_approved' as BusinessEventType,
      userId: approverId,
      referenceId: contractDocId,
      referenceTable: 'documents',
      summary: { title: `계약서 자동 생성됨 (견적서 승인 기반)` },
    });

    // ── Auto-seal + signature request for the new contract ──
    try {
      // Fetch deal + partner info for signature
      const { data: deal } = await db
        .from('deals')
        .select('name, partners!deals_partner_id_fkey(name, contact_email, contact_phone)')
        .eq('id', doc.deal_id)
        .single();

      const partnerEmail = deal?.partners?.contact_email || '';
      const partnerName = deal?.partners?.name || '';

      // Auto-apply company seal if available
      try {
        await applyCompanySeal({
          documentId: contractDocId,
          companyId,
          appliedBy: approverId,
        });
        await dispatchBusinessEvent({
          dealId: doc.deal_id,
          eventType: 'document_approved' as BusinessEventType,
          userId: approverId,
          referenceId: contractDocId,
          referenceTable: 'documents',
          summary: { title: `계약서 직인 자동 적용` },
        });
      } catch {
        // No seal configured — skip silently
      }

      // Send signature request if partner has a valid email
      if (partnerEmail && partnerEmail.includes('@')) {
        const sigReq = await createSignatureRequest({
          companyId,
          documentId: contractDocId,
          title: `${deal?.name || '계약'} - 계약서 서명 요청`,
          signerName: partnerName,
          signerEmail: partnerEmail,
          createdBy: approverId,
        });

        await sendSignatureEmail(sigReq.id);

        await dispatchBusinessEvent({
          dealId: doc.deal_id,
          eventType: 'document_approved' as BusinessEventType,
          userId: approverId,
          referenceId: sigReq.id,
          referenceTable: 'signature_requests',
          summary: { title: `서명 요청 자동 발송 (${partnerEmail})` },
        });
      }
    } catch (sigErr) {
      // Signature sending failure should not block the pipeline
      console.error('Auto-signature request failed:', sigErr);
    }

    return { nextAction: 'contract_created', createdDocId: contractDocId };
  }

  // CASE B: 계약서 승인 → 계약서 PDF 생성 + revenue_schedule 먼저 생성 → 세금계산서 연결
  if (docType === 'contract') {
    // Generate the contract PDF HTML and store as a document record
    const contractPdfResult = await generateContractDocumentForDeal({
      dealId: doc.deal_id,
      documentId,
      companyId,
      content,
      createdBy: approverId,
    });

    const result = await onContractApproved({
      dealId: doc.deal_id,
      companyId,
      userId: approverId,
      contractTotal: Number(content?.contractTotal || content?.supplyAmount || 0),
      partnerName: content?.partnerName || '',
      partnerBizNo: content?.partnerBizNo || '',
      paymentSchedule: content?.paymentSchedule || null,
      paymentRatio: content?.paymentRatio || null,
    });

    return {
      nextAction: 'tax_invoice_and_schedule_created',
      createdInvoiceId: result.invoiceIds?.[0] || undefined,
      createdDocId: contractPdfResult.pdfDocId,
    };
  }

  return {};
}

// ── 2b. Generate contract PDF when contract is approved ──

async function generateContractDocumentForDeal(params: {
  dealId: string;
  documentId: string;
  companyId: string;
  content: any;
  createdBy: string;
}): Promise<{ pdfDocId?: string }> {
  const { dealId, documentId, companyId, content, createdBy } = params;

  try {
    // Fetch company info
    const { data: company } = await db
      .from('companies')
      .select('name, business_number, representative, address, phone')
      .eq('id', companyId)
      .single();

    // Build items list for the contract
    const items = (content?.items || []).map((it: any) => ({
      name: it.name || '',
      spec: it.spec || '',
      qty: Number(it.quantity || it.qty || 1),
      unitPrice: Number(it.unitPrice || 0),
      amount: Number(it.supplyAmount || it.amount || it.totalAmount || 0),
    }));

    const contractTotal = Number(content?.contractTotal || content?.supplyAmount || 0);

    const pdfHtml = generateContractPDF({
      documentNumber: content?.documentNumber || `CTR-${dealId.slice(0, 8).toUpperCase()}`,
      date: new Date().toLocaleDateString('ko-KR'),
      partyA: {
        name: company?.name || '',
        representative: company?.representative || '',
        businessNumber: company?.business_number || '',
        address: company?.address || '',
        phone: company?.phone || '',
      },
      partyB: {
        name: content?.partnerName || '',
        representative: content?.counterpartyRepresentative || '',
        businessNumber: content?.partnerBizNo || '',
        address: content?.counterpartyAddress || '',
      },
      contractAmount: contractTotal,
      taxAmount: Math.round(contractTotal * 0.1),
      totalAmount: Math.round(contractTotal * 1.1),
      items,
      contractSubject: content?.dealName || '',
      contractStartDate: content?.contractStartDate || new Date().toISOString().split('T')[0],
      contractEndDate: content?.contractEndDate || '',
      paymentTerms: content?.paymentTerms || '',
      deliveryDeadline: content?.deliveryDeadline || '',
      inspectionPeriod: content?.inspectionPeriod || '7영업일',
      warrantyPeriod: content?.warrantyPeriod || '납품 후 1년',
      latePenaltyRate: content?.latePenaltyRate || '0.1',
      specialTerms: content?.specialTerms || '',
    });

    // Store the generated PDF HTML as a document record linked to the deal
    const { data: pdfDoc } = await db
      .from('documents')
      .insert({
        company_id: companyId,
        deal_id: dealId,
        name: `${content?.dealName || '계약'} - 계약서 (PDF)`,
        status: 'issued',
        content_json: {
          type: 'contract_pdf',
          sourceDocumentId: documentId,
          pdfHtml: pdfHtml,
          generatedAt: new Date().toISOString(),
          metadata: { autoGenerated: true, sourceDocType: 'contract' },
        },
        content_type: 'contract_pdf',
        version: 1,
        created_by: createdBy,
      })
      .select('id')
      .single();

    return { pdfDocId: pdfDoc?.id };
  } catch (err) {
    // Contract PDF generation failure should not block the pipeline
    console.error('Contract PDF generation failed:', err);
    return {};
  }
}

// ── 3. On contract approved — issue tax invoice + payment schedule ──

async function onContractApproved(params: {
  dealId: string;
  companyId: string;
  userId: string;
  contractTotal: number;
  partnerName: string;
  partnerBizNo: string;
  paymentSchedule?: any[] | null;
  paymentRatio?: { advance: number; balance: number } | null;
}) {
  const { dealId, companyId, userId, contractTotal, partnerName, partnerBizNo, paymentSchedule, paymentRatio } = params;
  const invoiceIds: string[] = [];

  if (contractTotal <= 0) return { invoiceIds };

  // ★ 핵심 순서: revenue_schedule 먼저 생성 → 생성된 row id 받기 → 세금계산서 draft에 연결

  // Step 1: paymentSchedule 결정 — use custom ratio if no explicit schedule provided
  const advRatio = paymentRatio?.advance ?? 30;
  const balRatio = paymentRatio?.balance ?? 70;
  const schedule = (paymentSchedule && Array.isArray(paymentSchedule) && paymentSchedule.length > 0)
    ? paymentSchedule
    : [
        { label: '선금', ratio: advRatio, amount: Math.round(contractTotal * advRatio / 100), condition: '계약 후 7일 이내' },
        { label: '잔금', ratio: balRatio, amount: contractTotal - Math.round(contractTotal * advRatio / 100), condition: '납품 완료 후 14일 이내' },
      ];

  // Step 2: revenue_schedule rows 먼저 생성
  const createdScheduleIds = await createPaymentScheduleFromContract({
    dealId,
    companyId,
    contractTotal,
    userId,
    schedule,
  });

  // Step 3: 각 revenue_schedule에 대응하는 세금계산서 생성
  // 선금(첫 번째)은 즉시 issued, 나머지(잔금)는 draft로 생성
  for (let i = 0; i < schedule.length; i++) {
    const term = schedule[i];
    if (term.amount <= 0) continue;

    const revenueScheduleId = createdScheduleIds[i] || null;
    const isFirstPayment = i === 0;
    const invoice = await createTaxInvoice({
      companyId,
      dealId,
      type: 'sales',
      counterpartyName: partnerName,
      counterpartyBizno: partnerBizNo,
      supplyAmount: term.amount,
      issueDate: new Date().toISOString().split('T')[0],
      label: `${term.label} 세금계산서`,
      revenueScheduleId,
      status: isFirstPayment ? 'issued' : 'draft',
    });

    if (invoice?.id) {
      invoiceIds.push(invoice.id);
      await dispatchBusinessEvent({
        dealId,
        eventType: 'invoice_issued' as BusinessEventType,
        userId,
        referenceId: invoice.id,
        referenceTable: 'tax_invoices',
        summary: {
          amount: Math.round(term.amount * 1.1),
          title: `${term.label} 세금계산서 자동 생성 (${isFirstPayment ? 'issued' : 'draft'})`,
        },
      });
    }
  }

  return { invoiceIds };
}

// ── 4. Create payment schedule (선금/잔금) ──

async function createPaymentScheduleFromContract(params: {
  dealId: string;
  companyId: string;
  contractTotal: number;
  userId: string;
  schedule: Array<{ label: string; ratio: number; amount: number; condition: string }>;
}): Promise<string[]> {
  const { dealId, companyId, contractTotal, userId, schedule } = params;
  if (contractTotal <= 0) return [];

  const now = new Date();
  const createdIds: string[] = [];

  // Insert revenue schedule entries one by one to get IDs back
  for (let i = 0; i < schedule.length; i++) {
    const term = schedule[i];
    const dueDate = new Date(now.getTime() + (i === 0 ? 7 : 60) * 24 * 60 * 60 * 1000);

    const { data: row } = await db
      .from('deal_revenue_schedule')
      .insert({
        deal_id: dealId,
        label: `${term.label} (${term.ratio}%)`,
        amount: term.amount,
        due_date: dueDate.toISOString().split('T')[0],
        status: 'expected',
        condition_text: term.condition,
      })
      .select('id')
      .single();

    if (row?.id) createdIds.push(row.id);
  }

  // Create payment queue entry for first payment
  const firstTerm = schedule[0];
  if (firstTerm) {
    await createQueueEntry({
      companyId,
      dealId,
      amount: firstTerm.amount,
      description: `${firstTerm.label} ${firstTerm.ratio}% 입금 예정 (D+7)`,
      costType: 'revenue',
    });
  }

  const scheduleDesc = schedule.map(t => `${t.label} ${t.amount.toLocaleString()}원`).join(' / ');
  await dispatchBusinessEvent({
    dealId,
    eventType: 'milestone_completed' as BusinessEventType,
    userId,
    referenceId: dealId,
    referenceTable: 'deals',
    summary: { title: `매출 스케줄 생성: ${scheduleDesc}` },
  });

  return createdIds;
}

// ── 5. On revenue received — 3-way match + deal update ──

export async function onRevenueReceived(params: {
  dealId: string;
  companyId: string;
  amount: number;
  userId: string;
  revenueScheduleId?: string;
}) {
  const { dealId, companyId, amount, userId, revenueScheduleId } = params;

  // Mark revenue schedule as received
  if (revenueScheduleId) {
    await db
      .from('deal_revenue_schedule')
      .update({
        status: 'received',
        received_date: new Date().toISOString().split('T')[0],
      })
      .eq('id', revenueScheduleId);

    // revenue_schedule_id로 연결된 세금계산서 자동 매칭
    const { data: linkedInvoice } = await db
      .from('tax_invoices')
      .select('id')
      .eq('revenue_schedule_id', revenueScheduleId)
      .single();
    if (linkedInvoice) {
      await markInvoiceMatched(linkedInvoice.id);
    }

    // 선금 입금 후 → 다음 스케줄의 draft 세금계산서를 자동 issued 전환
    const { data: nextDraftInvoices } = await db
      .from('tax_invoices')
      .select('id, revenue_schedule_id')
      .eq('deal_id', dealId)
      .eq('status', 'draft')
      .not('revenue_schedule_id', 'is', null)
      .order('created_at', { ascending: true })
      .limit(1);
    if (nextDraftInvoices && nextDraftInvoices.length > 0) {
      await issueTaxInvoice(nextDraftInvoices[0].id);
    }
  }

  // Check if all revenue received
  const { data: schedules } = await db
    .from('deal_revenue_schedule')
    .select('id, amount, status')
    .eq('deal_id', dealId);

  const allReceived = (schedules || []).every((s: { status: string }) => s.status === 'received');
  const totalExpected = (schedules || []).reduce(
    (sum: number, s: { amount: number }) => sum + Number(s.amount || 0), 0
  );
  const totalReceived = (schedules || [])
    .filter((s: { status: string }) => s.status === 'received')
    .reduce((sum: number, s: { amount: number }) => sum + Number(s.amount || 0), 0);

  // Update deal status if fully paid
  if (allReceived && totalReceived >= totalExpected) {
    await db
      .from('deals')
      .update({ status: 'completed', last_activity_at: new Date().toISOString() })
      .eq('id', dealId);

    await dispatchBusinessEvent({
      dealId,
      eventType: 'deal_status_changed' as BusinessEventType,
      userId,
      referenceId: dealId,
      referenceTable: 'deals',
      summary: { from: 'active', to: 'completed', reason: '전액 입금 완료' },
    });
  }

  // Dispatch payment received event
  await dispatchBusinessEvent({
    dealId,
    eventType: 'payment_received' as BusinessEventType,
    userId,
    referenceId: revenueScheduleId || dealId,
    referenceTable: revenueScheduleId ? 'deal_revenue_schedule' : 'deals',
    summary: {
      amount,
      totalReceived,
      totalExpected,
      progress: totalExpected > 0 ? Math.round((totalReceived / totalExpected) * 100) : 0,
    },
  });
}

// ── 6. Get pipeline status for a deal ──

export async function getDealPipelineStatus(dealId: string): Promise<PipelineStage[]> {
  // Get all documents linked to this deal
  const { data: docs } = await (supabase as any)
    .from('documents')
    .select('id, name, status, content_json, created_at, updated_at')
    .eq('deal_id', dealId)
    .order('created_at', { ascending: true });

  // Get tax invoices for this deal
  const { data: invoices } = await supabase
    .from('tax_invoices')
    .select('id, status, total_amount, issue_date')
    .eq('deal_id', dealId)
    .neq('status', 'void');

  // Get revenue schedule
  const { data: schedules } = await db
    .from('deal_revenue_schedule')
    .select('id, status, amount')
    .eq('deal_id', dealId);

  const stages: PipelineStage[] = [];

  // Stage 1: Quote/Invoice document
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const quoteDoc = (docs || []).find((d: any) => {
    const ct = d.content_json as any;
    return ct?.type === 'invoice' || ct?.type === 'quote';
  });
  stages.push({
    stage: 'quote',
    status: !quoteDoc ? 'pending' : quoteDoc.status === 'approved' || quoteDoc.status === 'locked' ? 'completed' : 'active',
    documentId: quoteDoc?.id,
    completedAt: quoteDoc?.status === 'approved' ? (quoteDoc.updated_at ?? quoteDoc.created_at ?? undefined) : undefined,
  });

  // Stage 2: Contract document
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const contractDoc = (docs || []).find((d: any) => {
    const ct = d.content_json as any;
    return ct?.type === 'contract';
  });
  stages.push({
    stage: 'contract',
    status: !contractDoc ? 'pending' : contractDoc.status === 'approved' || contractDoc.status === 'locked' ? 'completed' : 'active',
    documentId: contractDoc?.id,
    completedAt: contractDoc?.status === 'approved' ? (contractDoc.created_at ?? undefined) : undefined,
  });

  // Stage 3: Tax invoice
  const hasInvoice = (invoices || []).length > 0;
  stages.push({
    stage: 'tax_invoice',
    status: !hasInvoice ? 'pending' : 'completed',
    documentId: invoices?.[0]?.id,
  });

  // Stage 4: Payment schedule created
  const hasSchedule = (schedules || []).length > 0;
  stages.push({
    stage: 'payment_schedule',
    status: !hasSchedule ? 'pending' : 'completed',
  });

  // Stage 5: Payment received
  const allPaid = hasSchedule && (schedules || []).every((s: { status: string }) => s.status === 'received');
  stages.push({
    stage: 'payment_received',
    status: allPaid ? 'completed' : hasSchedule ? 'active' : 'pending',
  });

  return stages;
}

// ── 7. Force Approve (임의승인) — 업체 응답 없을 때 우리가 직접 승인 ──

export async function forceApproveDocument(params: {
  documentId: string;
  companyId: string;
  approverId: string;
  reason?: string;
}): Promise<{ nextAction?: string; createdDocId?: string; createdInvoiceId?: string }> {
  const { documentId, companyId, approverId, reason } = params;

  // Fetch current document
  const { data: doc } = await supabase
    .from('documents')
    .select('id, name, status, deal_id, content_json')
    .eq('id', documentId)
    .single();

  if (!doc) throw new Error('문서를 찾을 수 없습니다');

  // Update status to approved + record force approval info in content_json
  const existingContent = (doc.content_json as Record<string, unknown>) || {};
  const { error } = await supabase
    .from('documents')
    .update({
      status: 'approved',
      content_json: {
        ...existingContent,
        forceApproval: {
          approved: true,
          approvedBy: approverId,
          approvedAt: new Date().toISOString(),
          reason: reason || '업체 미응답으로 임의 승인',
        },
      } as unknown as Json,
    })
    .eq('id', documentId);

  if (error) throw error;

  if (doc.deal_id) {
    await dispatchBusinessEvent({
      dealId: doc.deal_id,
      eventType: 'document_approved' as BusinessEventType,
      userId: approverId,
      referenceId: documentId,
      referenceTable: 'documents',
      summary: { title: `${doc.name} 임의 승인 (사유: ${reason || '업체 미응답'})` },
    });
  }

  // Trigger normal pipeline (계약서 자동생성 or 세금계산서 발행)
  if (doc.deal_id) {
    return onDocumentApproved({ documentId, companyId, approverId });
  }

  return { nextAction: 'force_approved' };
}
