import { NextRequest, NextResponse } from 'next/server';
import { createSupabaseServerClient } from '@/lib/supabase-server';
import { createSupabaseAdminClient } from '@/lib/supabase-admin';
import { assertSameOrigin } from '@/lib/api-authz';
import { buildContractArchiveHtml } from '@/lib/contract-html';

// 계약 보관본(content_type='contract_pdf') — 서버가 직접 렌더링해 만든다 (2026-10-01).
//   History: 계약 승인 때 deal-pipeline(브라우저)이 HTML 을 만들어 넣었다 → 9/30 가드 예외(issued+contract_pdf) → 오늘 오전
//   archive_contract_pdf RPC 로 좁혔지만 HTML 은 여전히 승인자 브라우저 값이었다. 이제 입력은 원본 계약서 id 하나,
//   본문·회사 정보는 서버가 DB 에서 읽고 렌더링도 서버(같은 함수 contract-html.ts)에서 한다.
//   규칙: 로그인 사용자의 회사 · 계약서 · 승인(잠금/체결/발행) 상태 · 원본당 1건(있으면 그 id). 세무대리인 불가.
export async function POST(request: NextRequest) {
  { const csrf = assertSameOrigin(request); if (csrf) return csrf; }
  try {
    const supabase = await createSupabaseServerClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return NextResponse.json({ error: { code: 'UNAUTHORIZED', message: '인증이 필요합니다' } }, { status: 401 });

    const body = await request.json().catch(() => ({}));
    const documentId = String(body?.documentId || '');
    if (!/^[0-9a-f-]{36}$/i.test(documentId)) {
      return NextResponse.json({ error: { code: 'VALIDATION_ERROR', message: '계약서를 지정해 주세요' } }, { status: 400 });
    }

    //   세무대리인 세션은 사용자 세션 함수로 판단(서버 클라이언트 = 그 사람 권한)
    const { data: isAdvisor } = await supabase.rpc('is_advisor_session');
    if (isAdvisor) return NextResponse.json({ error: { code: 'FORBIDDEN', message: '세무대리인은 계약 보관본을 만들 수 없습니다' } }, { status: 403 });

    const admin = createSupabaseAdminClient();
    const { data: me } = await admin.from('users').select('id, company_id').eq('auth_id', user.id).maybeSingle();
    if (!me?.id || !me.company_id) return NextResponse.json({ error: { code: 'FORBIDDEN', message: '사용자 정보를 찾을 수 없습니다' } }, { status: 403 });

    const { data: src } = await admin.from('documents')
      .select('id, company_id, deal_id, name, status, content_type, content_json').eq('id', documentId).maybeSingle();
    if (!src || src.company_id !== me.company_id) {
      return NextResponse.json({ error: { code: 'NOT_FOUND', message: '계약서를 찾을 수 없습니다' } }, { status: 404 });
    }
    const content = (src.content_json || {}) as Record<string, any>;
    if ((src.content_type || content.type || '') !== 'contract') {
      return NextResponse.json({ error: { code: 'VALIDATION_ERROR', message: '계약서만 보관본을 만들 수 있습니다' } }, { status: 400 });
    }
    if (!['approved', 'locked', 'executed', 'issued'].includes(String(src.status || ''))) {
      return NextResponse.json({ error: { code: 'VALIDATION_ERROR', message: '승인된 계약서만 보관본을 만들 수 있습니다' } }, { status: 400 });
    }

    const { data: existing } = await admin.from('documents').select('id')
      .eq('company_id', me.company_id).eq('content_type', 'contract_pdf')
      .eq('content_json->>sourceDocumentId', documentId).limit(1).maybeSingle();
    if (existing?.id) return NextResponse.json({ data: { id: existing.id, existed: true } });

    const { data: company } = await admin.from('companies')
      .select('name, business_number, representative, address, phone').eq('id', me.company_id).maybeSingle();
    const pdfHtml = buildContractArchiveHtml({ dealId: src.deal_id, content, company });

    const now = new Date().toISOString();
    const { data: created, error } = await admin.from('documents').insert({
      company_id: me.company_id,
      deal_id: src.deal_id,
      name: `${content.dealName || src.name || '계약'} - 계약서 (PDF)`.slice(0, 200),
      status: 'issued',
      content_type: 'contract_pdf',
      content_json: {
        type: 'contract_pdf',
        sourceDocumentId: documentId,
        pdfHtml,
        generatedAt: now,
        metadata: { autoGenerated: true, sourceDocType: 'contract', renderedBy: 'server' },
      },
      version: 1,
      created_by: me.id,
      issued_at: now,
      locked_at: now,
    }).select('id').single();
    if (error) {
      //   동시에 두 번 불리면 원본당 1건 고유 색인(documents_contract_pdf_source_uniq)에 걸린다 — 먼저 만든 것을 돌려준다
      if ((error as { code?: string }).code === '23505') {
        const { data: again } = await admin.from('documents').select('id')
          .eq('company_id', me.company_id).eq('content_type', 'contract_pdf')
          .eq('content_json->>sourceDocumentId', documentId).limit(1).maybeSingle();
        if (again?.id) return NextResponse.json({ data: { id: again.id, existed: true } });
      }
      throw error;
    }
    return NextResponse.json({ data: { id: created.id, existed: false } });
  } catch (e) {
    console.error('[documents/archive-contract]', e);
    return NextResponse.json({ error: { code: 'INTERNAL', message: '계약 보관본을 만들지 못했습니다' } }, { status: 500 });
  }
}
