-- RLS 성능 최적화 (2026-06-05) — auth.uid()/get_my_company_id() 를 (select ...) 로 래핑.
-- 행마다 인증 재평가 → 쿼리당 1회(initplan). 동일 의미, 순수 성능. advisor auth_rls_initplan 86→9.
-- 232개 정책 일괄. (Management API 로 prod 적용 완료)
ALTER POLICY "ai_interactions_company" ON public."ai_interactions" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "ai_pending_actions_company" ON public."ai_pending_actions" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "allowance_entries_admin_delete" ON public."allowance_entries" USING (((company_id = ( SELECT get_my_company_id() )) AND is_company_admin()));
ALTER POLICY "allowance_entries_admin_insert" ON public."allowance_entries" WITH CHECK (((company_id = ( SELECT get_my_company_id() )) AND is_company_admin()));
ALTER POLICY "allowance_entries_admin_update" ON public."allowance_entries" USING (((company_id = ( SELECT get_my_company_id() )) AND is_company_admin())) WITH CHECK (((company_id = ( SELECT get_my_company_id() )) AND is_company_admin()));
ALTER POLICY "allowance_entries_select_self_or_admin" ON public."allowance_entries" USING (((company_id = ( SELECT get_my_company_id() )) AND (is_company_admin() OR (employee_id = current_employee_id()))));
ALTER POLICY "allowance_types_admin_write" ON public."allowance_types" USING (((company_id = ( SELECT get_my_company_id() )) AND is_company_admin())) WITH CHECK (((company_id = ( SELECT get_my_company_id() )) AND is_company_admin()));
ALTER POLICY "allowance_types_select_company" ON public."allowance_types" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "announcements_write_operator" ON public."announcements" USING ((EXISTS ( SELECT 1 FROM users u WHERE ((u.auth_id = ( SELECT auth.uid() )) AND (u.email ~~ '%@mo-tive.com'::text))))) WITH CHECK ((EXISTS ( SELECT 1 FROM users u WHERE ((u.auth_id = ( SELECT auth.uid() )) AND (u.email ~~ '%@mo-tive.com'::text)))));
ALTER POLICY "approval_policies_company" ON public."approval_policies" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "Company members can delete approval requests" ON public."approval_requests" USING ((company_id = ( SELECT users.company_id FROM users WHERE (users.auth_id = ( SELECT auth.uid() )))));
ALTER POLICY "Company members can insert approval requests" ON public."approval_requests" WITH CHECK ((company_id IN ( SELECT users.company_id FROM users WHERE (users.auth_id = ( SELECT auth.uid() )))));
ALTER POLICY "Company members can update approval requests" ON public."approval_requests" USING ((company_id IN ( SELECT users.company_id FROM users WHERE (users.auth_id = ( SELECT auth.uid() )))));
ALTER POLICY "Company members can view approval requests" ON public."approval_requests" USING ((company_id IN ( SELECT users.company_id FROM users WHERE (users.auth_id = ( SELECT auth.uid() )))));
ALTER POLICY "Approval steps insertable by company members" ON public."approval_steps" WITH CHECK ((request_id IN ( SELECT approval_requests.id FROM approval_requests WHERE (approval_requests.company_id IN ( SELECT users.company_id FROM users WHERE (users.auth_id = ( SELECT auth.uid() )))))));
ALTER POLICY "Approval steps updatable by approvers" ON public."approval_steps" USING ((approver_id IN ( SELECT users.id FROM users WHERE (users.auth_id = ( SELECT auth.uid() )))));
ALTER POLICY "Approval steps viewable by company members" ON public."approval_steps" USING ((request_id IN ( SELECT approval_requests.id FROM approval_requests WHERE (approval_requests.company_id IN ( SELECT users.company_id FROM users WHERE (users.auth_id = ( SELECT auth.uid() )))))));
ALTER POLICY "aer_insert" ON public."attendance_edit_requests" WITH CHECK (((company_id = ( SELECT get_my_company_id() )) AND (requested_by = current_app_user_id())));
ALTER POLICY "aer_select" ON public."attendance_edit_requests" USING (((company_id = ( SELECT get_my_company_id() )) AND (is_company_admin() OR (requested_by = current_app_user_id()))));
ALTER POLICY "aer_update_admin" ON public."attendance_edit_requests" USING ((is_company_admin() AND (company_id = ( SELECT get_my_company_id() )))) WITH CHECK ((is_company_admin() AND (company_id = ( SELECT get_my_company_id() ))));
ALTER POLICY "attendance_records_delete" ON public."attendance_records" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "attendance_records_insert" ON public."attendance_records" WITH CHECK ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "attendance_records_select" ON public."attendance_records" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "attendance_records_update" ON public."attendance_records" USING ((company_id = ( SELECT get_my_company_id() ))) WITH CHECK ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "Users can view audit logs for their company" ON public."audit_logs" USING ((company_id IN ( SELECT users.company_id FROM users WHERE (users.auth_id = ( SELECT auth.uid() )))));
ALTER POLICY "audit_logs_company_access" ON public."audit_logs" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "auto_discovery_company" ON public."auto_discovery_results" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "company_delete" ON public."automation_credentials" USING (((company_id = ( SELECT get_my_company_id() )) AND (EXISTS ( SELECT 1 FROM users WHERE ((users.auth_id = ( SELECT auth.uid() )) AND (users.role = ANY (ARRAY['owner'::text, 'admin'::text])))))));
ALTER POLICY "company_insert" ON public."automation_credentials" WITH CHECK (((company_id = ( SELECT get_my_company_id() )) AND (EXISTS ( SELECT 1 FROM users WHERE ((users.auth_id = ( SELECT auth.uid() )) AND (users.role = ANY (ARRAY['owner'::text, 'admin'::text])))))));
ALTER POLICY "company_select" ON public."automation_credentials" USING (((company_id = ( SELECT get_my_company_id() )) AND (EXISTS ( SELECT 1 FROM users WHERE ((users.auth_id = ( SELECT auth.uid() )) AND (users.role = ANY (ARRAY['owner'::text, 'admin'::text])))))));
ALTER POLICY "company_update" ON public."automation_credentials" USING (((company_id = ( SELECT get_my_company_id() )) AND (EXISTS ( SELECT 1 FROM users WHERE ((users.auth_id = ( SELECT auth.uid() )) AND (users.role = ANY (ARRAY['owner'::text, 'admin'::text])))))));
ALTER POLICY "Users can view own company automation_logs" ON public."automation_logs" USING ((company_id IN ( SELECT (users.company_id)::text AS company_id FROM users WHERE (users.auth_id = ( SELECT auth.uid() )))));
ALTER POLICY "automation_runs_company" ON public."automation_runs" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "Company members can manage bank accounts" ON public."bank_accounts" USING ((company_id = ( SELECT get_my_company_id() ))) WITH CHECK ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "Company members can view bank accounts" ON public."bank_accounts" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "company_isolation" ON public."bank_classification_rules" USING ((company_id = ( SELECT get_my_company_id() AS get_my_company_id)));
ALTER POLICY "company_isolation" ON public."bank_transactions" USING ((company_id = ( SELECT get_my_company_id() AS get_my_company_id)));
ALTER POLICY "System can insert billing events" ON public."billing_events" WITH CHECK ((company_id IN ( SELECT users.company_id FROM users WHERE (users.auth_id = ( SELECT auth.uid() )))));
ALTER POLICY "Users can insert own billing_events" ON public."billing_events" WITH CHECK ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "Users can read own billing events" ON public."billing_events" USING ((company_id IN ( SELECT users.company_id FROM users WHERE (users.auth_id = ( SELECT auth.uid() )))));
ALTER POLICY "Users can read own billing_events" ON public."billing_events" USING (((company_id = ( SELECT get_my_company_id() )) OR (auth.role() = 'service_role'::text)));
ALTER POLICY "board_comments_company" ON public."board_comments" USING ((company_id = ( SELECT get_my_company_id() ))) WITH CHECK ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "board_poll_votes_delete" ON public."board_poll_votes" USING (((company_id = ( SELECT get_my_company_id() AS get_my_company_id)) AND (user_id = ( SELECT users.id FROM users WHERE (users.auth_id = ( SELECT auth.uid() AS uid))))));
ALTER POLICY "board_poll_votes_insert" ON public."board_poll_votes" WITH CHECK (((company_id = ( SELECT get_my_company_id() AS get_my_company_id)) AND (user_id = ( SELECT users.id FROM users WHERE (users.auth_id = ( SELECT auth.uid() AS uid))))));
ALTER POLICY "board_poll_votes_select" ON public."board_poll_votes" USING ((company_id = ( SELECT get_my_company_id() AS get_my_company_id)));
ALTER POLICY "board_poll_votes_update" ON public."board_poll_votes" USING (((company_id = ( SELECT get_my_company_id() AS get_my_company_id)) AND (user_id = ( SELECT users.id FROM users WHERE (users.auth_id = ( SELECT auth.uid() AS uid)))))) WITH CHECK (((company_id = ( SELECT get_my_company_id() AS get_my_company_id)) AND (user_id = ( SELECT users.id FROM users WHERE (users.auth_id = ( SELECT auth.uid() AS uid))))));
ALTER POLICY "board_posts_company" ON public."board_posts" USING ((company_id = ( SELECT get_my_company_id() ))) WITH CHECK ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "Company can manage card_aliases" ON public."card_aliases" USING ((company_id = ( SELECT get_my_company_id() ))) WITH CHECK ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "company_isolation" ON public."card_transactions" USING ((company_id = ( SELECT get_my_company_id() AS get_my_company_id)));
ALTER POLICY "Users can delete own company cash receipts" ON public."cash_receipts" USING ((company_id IN ( SELECT users.company_id FROM users WHERE (users.id = ( SELECT auth.uid() )))));
ALTER POLICY "Users can insert own company cash receipts" ON public."cash_receipts" WITH CHECK ((company_id IN ( SELECT users.company_id FROM users WHERE (users.id = ( SELECT auth.uid() )))));
ALTER POLICY "Users can update own company cash receipts" ON public."cash_receipts" USING ((company_id IN ( SELECT users.company_id FROM users WHERE (users.id = ( SELECT auth.uid() )))));
ALTER POLICY "Users can view own company cash receipts" ON public."cash_receipts" USING ((company_id IN ( SELECT users.company_id FROM users WHERE (users.id = ( SELECT auth.uid() )))));
ALTER POLICY "Company can manage cash" ON public."cash_snapshot" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "Users can insert cash_snapshot for own company" ON public."cash_snapshot" WITH CHECK ((company_id IN ( SELECT users.company_id FROM users WHERE (users.auth_id = ( SELECT auth.uid() )))));
ALTER POLICY "company_isolation" ON public."certificate_logs" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "participant_only" ON public."chat_action_cards" USING ((channel_id IN ( SELECT cp.channel_id FROM (chat_participants cp JOIN users u ON ((cp.user_id = u.id))) WHERE (u.auth_id = ( SELECT auth.uid() )))));
ALTER POLICY "chat_channels_company" ON public."chat_channels" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "chat_events_company" ON public."chat_events" USING ((channel_id IN ( SELECT chat_channels.id FROM chat_channels WHERE (chat_channels.company_id = ( SELECT get_my_company_id() )))));
ALTER POLICY "chat_files_company" ON public."chat_files" USING ((channel_id IN ( SELECT chat_channels.id FROM chat_channels WHERE (chat_channels.company_id = ( SELECT get_my_company_id() )))));
ALTER POLICY "chat_members_company" ON public."chat_members" USING ((EXISTS ( SELECT 1 FROM chat_channels cc WHERE ((cc.id = chat_members.channel_id) AND (cc.company_id = ( SELECT get_my_company_id() ))))));
ALTER POLICY "participant_only" ON public."chat_mentions" USING ((channel_id IN ( SELECT cp.channel_id FROM (chat_participants cp JOIN users u ON ((cp.user_id = u.id))) WHERE (u.auth_id = ( SELECT auth.uid() )))));
ALTER POLICY "chat_messages_company" ON public."chat_messages" USING ((channel_id IN ( SELECT chat_channels.id FROM chat_channels WHERE (chat_channels.company_id = ( SELECT get_my_company_id() )))));
ALTER POLICY "chat_participants_company" ON public."chat_participants" USING ((channel_id IN ( SELECT chat_channels.id FROM chat_channels WHERE (chat_channels.company_id = ( SELECT get_my_company_id() )))));
ALTER POLICY "participant_only" ON public."chat_reactions" USING ((user_id IN ( SELECT users.id FROM users WHERE (users.auth_id = ( SELECT auth.uid() )))));
ALTER POLICY "checklist_access" ON public."closing_checklist_items" USING ((checklist_id IN ( SELECT closing_checklists.id FROM closing_checklists WHERE (closing_checklists.company_id = ( SELECT get_my_company_id() AS get_my_company_id)))));
ALTER POLICY "company_isolation" ON public."closing_checklists" USING ((company_id = ( SELECT get_my_company_id() AS get_my_company_id)));
ALTER POLICY "Owners can update company" ON public."companies" USING ((id = ( SELECT get_my_company_id() ))) WITH CHECK ((id = ( SELECT get_my_company_id() )));
ALTER POLICY "Users can view own company" ON public."companies" USING ((id = ( SELECT get_my_company_id() )));
ALTER POLICY "company_integrations_policy" ON public."company_integrations" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "company_settings_access" ON public."company_settings" USING ((company_id = ( SELECT get_my_company_id() ))) WITH CHECK ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "contract_archives_company" ON public."contract_archives" USING ((company_id IN ( SELECT employees.company_id FROM employees WHERE (employees.user_id = ( SELECT auth.uid() )))));
ALTER POLICY "contract_templates_admin_delete" ON public."contract_templates" USING (((is_system = false) AND (company_id = ( SELECT get_my_company_id() )) AND is_company_admin()));
ALTER POLICY "contract_templates_admin_insert" ON public."contract_templates" WITH CHECK (((is_system = false) AND (company_id = ( SELECT get_my_company_id() )) AND is_company_admin()));
ALTER POLICY "contract_templates_admin_update" ON public."contract_templates" USING (((is_system = false) AND (company_id = ( SELECT get_my_company_id() )) AND is_company_admin())) WITH CHECK (((is_system = false) AND (company_id = ( SELECT get_my_company_id() )) AND is_company_admin()));
ALTER POLICY "contract_templates_select_system_or_company" ON public."contract_templates" USING (((is_system = true) OR (company_id = ( SELECT get_my_company_id() ))));
ALTER POLICY "company_isolation" ON public."corporate_cards" USING ((company_id = ( SELECT get_my_company_id() AS get_my_company_id)));
ALTER POLICY "Company members can manage assignments" ON public."deal_assignments" USING ((EXISTS ( SELECT 1 FROM deals d WHERE ((d.id = deal_assignments.deal_id) AND (d.company_id = ( SELECT get_my_company_id() )))))) WITH CHECK ((EXISTS ( SELECT 1 FROM deals d WHERE ((d.id = deal_assignments.deal_id) AND (d.company_id = ( SELECT get_my_company_id() ))))));
ALTER POLICY "Company members can view assignments" ON public."deal_assignments" USING ((EXISTS ( SELECT 1 FROM deals d WHERE ((d.id = deal_assignments.deal_id) AND (d.company_id = ( SELECT get_my_company_id() ))))));
ALTER POLICY "deal_classifications_delete" ON public."deal_classifications" USING (((company_id = ( SELECT get_my_company_id() AS get_my_company_id)) AND (is_system = false)));
ALTER POLICY "deal_classifications_insert" ON public."deal_classifications" WITH CHECK ((company_id = ( SELECT get_my_company_id() AS get_my_company_id)));
ALTER POLICY "deal_classifications_select" ON public."deal_classifications" USING ((company_id = ( SELECT get_my_company_id() AS get_my_company_id)));
ALTER POLICY "deal_classifications_update" ON public."deal_classifications" USING ((company_id = ( SELECT get_my_company_id() AS get_my_company_id)));
ALTER POLICY "Company can manage costs" ON public."deal_cost_schedule" USING ((EXISTS ( SELECT 1 FROM (deal_nodes dn JOIN deals d ON ((d.id = dn.deal_id))) WHERE ((dn.id = deal_cost_schedule.deal_node_id) AND (d.company_id = ( SELECT get_my_company_id() ))))));
ALTER POLICY "deal_cost_schedule_company_isolation" ON public."deal_cost_schedule" USING ((company_id IN ( SELECT users.company_id FROM users WHERE (users.id = ( SELECT auth.uid() )))));
ALTER POLICY "deal_files_company" ON public."deal_files" USING ((company_id IN ( SELECT users.company_id FROM users WHERE (users.id = ( SELECT auth.uid() )))));
ALTER POLICY "Company members can manage milestones" ON public."deal_milestones" USING ((EXISTS ( SELECT 1 FROM deals d WHERE ((d.id = deal_milestones.deal_id) AND (d.company_id = ( SELECT get_my_company_id() )))))) WITH CHECK ((EXISTS ( SELECT 1 FROM deals d WHERE ((d.id = deal_milestones.deal_id) AND (d.company_id = ( SELECT get_my_company_id() ))))));
ALTER POLICY "Company members can view milestones" ON public."deal_milestones" USING ((EXISTS ( SELECT 1 FROM deals d WHERE ((d.id = deal_milestones.deal_id) AND (d.company_id = ( SELECT get_my_company_id() ))))));
ALTER POLICY "Company can manage nodes" ON public."deal_nodes" USING ((EXISTS ( SELECT 1 FROM deals d WHERE ((d.id = deal_nodes.deal_id) AND (d.company_id = ( SELECT get_my_company_id() ))))));
ALTER POLICY "Company can manage revenue" ON public."deal_revenue_schedule" USING ((EXISTS ( SELECT 1 FROM deals d WHERE ((d.id = deal_revenue_schedule.deal_id) AND (d.company_id = ( SELECT get_my_company_id() ))))));
ALTER POLICY "Company can manage deals" ON public."deals" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "Company members can manage approvals" ON public."doc_approvals" USING ((EXISTS ( SELECT 1 FROM documents d WHERE ((d.id = doc_approvals.document_id) AND (d.company_id = ( SELECT get_my_company_id() )))))) WITH CHECK ((EXISTS ( SELECT 1 FROM documents d WHERE ((d.id = doc_approvals.document_id) AND (d.company_id = ( SELECT get_my_company_id() ))))));
ALTER POLICY "Company members can view approvals" ON public."doc_approvals" USING ((EXISTS ( SELECT 1 FROM documents d WHERE ((d.id = doc_approvals.document_id) AND (d.company_id = ( SELECT get_my_company_id() ))))));
ALTER POLICY "Company members can manage revisions" ON public."doc_revisions" USING ((EXISTS ( SELECT 1 FROM documents d WHERE ((d.id = doc_revisions.document_id) AND (d.company_id = ( SELECT get_my_company_id() )))))) WITH CHECK ((EXISTS ( SELECT 1 FROM documents d WHERE ((d.id = doc_revisions.document_id) AND (d.company_id = ( SELECT get_my_company_id() ))))));
ALTER POLICY "Company members can view revisions" ON public."doc_revisions" USING ((EXISTS ( SELECT 1 FROM documents d WHERE ((d.id = doc_revisions.document_id) AND (d.company_id = ( SELECT get_my_company_id() ))))));
ALTER POLICY "Company members can manage doc templates" ON public."doc_templates" USING ((company_id = ( SELECT get_my_company_id() ))) WITH CHECK ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "Company members can view doc templates" ON public."doc_templates" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "document_files_company" ON public."document_files" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "document_files_company_isolation" ON public."document_files" USING ((company_id = ( SELECT get_my_company_id() AS get_my_company_id)));
ALTER POLICY "document_folders_company" ON public."document_folders" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "document_folders_company_isolation" ON public."document_folders" USING ((company_id = ( SELECT get_my_company_id() AS get_my_company_id)));
ALTER POLICY "doc_notifications_company" ON public."document_notifications" USING ((company_id IN ( SELECT employees.company_id FROM employees WHERE (employees.user_id = ( SELECT auth.uid() )))));
ALTER POLICY "company_members_manage_shares" ON public."document_shares" USING ((document_id IN ( SELECT documents.id FROM documents WHERE (documents.company_id = ( SELECT get_my_company_id() )))));
ALTER POLICY "Company members can manage documents" ON public."documents" USING ((company_id = ( SELECT get_my_company_id() ))) WITH CHECK ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "Company members can view documents" ON public."documents" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "employee_contracts_company" ON public."employee_contracts" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "employee_contracts_policy" ON public."employee_contracts" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "employee_files_company_admin" ON public."employee_files" USING ((employee_id IN ( SELECT employees.id FROM employees WHERE (employees.company_id = ( SELECT get_my_company_id() )))));
ALTER POLICY "employee_files_self_insert" ON public."employee_files" WITH CHECK ((employee_id IN ( SELECT employees.id FROM employees WHERE (employees.user_id = ( SELECT auth.uid() )))));
ALTER POLICY "employee_files_self_read" ON public."employee_files" USING ((employee_id IN ( SELECT employees.id FROM employees WHERE (employees.user_id = ( SELECT auth.uid() )))));
ALTER POLICY "employee_invitations_company_access" ON public."employee_invitations" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "Company can manage employees" ON public."employees" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "error_logs_operator_rw" ON public."error_logs" USING ((EXISTS ( SELECT 1 FROM users u WHERE ((u.auth_id = ( SELECT auth.uid() )) AND (u.email ~~ '%@mo-tive.com'::text))))) WITH CHECK ((EXISTS ( SELECT 1 FROM users u WHERE ((u.auth_id = ( SELECT auth.uid() )) AND (u.email ~~ '%@mo-tive.com'::text)))));
ALTER POLICY "expense_approvals_company" ON public."expense_approvals" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "expense_approvals_policy" ON public."expense_approvals" USING ((expense_id IN ( SELECT expense_requests.id FROM expense_requests WHERE (expense_requests.company_id = ( SELECT get_my_company_id() )))));
ALTER POLICY "expense_requests_company" ON public."expense_requests" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "Users can create feedback" ON public."feedback" WITH CHECK ((company_id IN ( SELECT users.company_id FROM users WHERE (users.auth_id = ( SELECT auth.uid() )))));
ALTER POLICY "Users can delete own feedback" ON public."feedback" USING ((user_id = ( SELECT auth.uid() )));
ALTER POLICY "Users can read own feedback" ON public."feedback" USING ((company_id IN ( SELECT users.company_id FROM users WHERE (users.auth_id = ( SELECT auth.uid() )))));
ALTER POLICY "Users can update own feedback" ON public."feedback" USING ((user_id IN ( SELECT users.id FROM users WHERE (users.auth_id = ( SELECT auth.uid() )))));
ALTER POLICY "company_isolation" ON public."finance_access_logs" USING ((company_id = ( SELECT get_my_company_id() AS get_my_company_id)));
ALTER POLICY "company_access" ON public."financial_items" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "company_access" ON public."growth_targets" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "holidays_select_company" ON public."holidays" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "holidays_write_admin" ON public."holidays" USING ((is_company_admin() AND (company_id = ( SELECT get_my_company_id() )))) WITH CHECK ((is_company_admin() AND (company_id = ( SELECT get_my_company_id() ))));
ALTER POLICY "Company can insert own sync jobs" ON public."hometax_sync_jobs" WITH CHECK ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "Company can read own sync jobs" ON public."hometax_sync_jobs" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "Company members can delete sync logs" ON public."hometax_sync_log" USING ((company_id = ( SELECT users.company_id FROM users WHERE (users.auth_id = ( SELECT auth.uid() )))));
ALTER POLICY "Company members can view sync logs" ON public."hometax_sync_log" USING ((company_id IN ( SELECT users.company_id FROM users WHERE (users.id = ( SELECT auth.uid() )))));
ALTER POLICY "hr_contract_package_items_access" ON public."hr_contract_package_items" USING ((package_id IN ( SELECT hr_contract_packages.id FROM hr_contract_packages WHERE (hr_contract_packages.company_id = ( SELECT get_my_company_id() )))));
ALTER POLICY "hr_contract_packages_company" ON public."hr_contract_packages" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "invoice_settlements_company_access" ON public."invoice_settlements" USING ((company_id = ( SELECT get_my_company_id() ))) WITH CHECK ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "System can manage invoices" ON public."invoices" USING ((company_id IN ( SELECT users.company_id FROM users WHERE ((users.auth_id = ( SELECT auth.uid() )) AND (users.role = ANY (ARRAY['owner'::text, 'admin'::text]))))));
ALTER POLICY "Users can read own invoices" ON public."invoices" USING ((company_id IN ( SELECT users.company_id FROM users WHERE (users.auth_id = ( SELECT auth.uid() )))));
ALTER POLICY "leave_balances_delete" ON public."leave_balances" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "leave_balances_insert" ON public."leave_balances" WITH CHECK ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "leave_balances_select" ON public."leave_balances" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "leave_balances_update" ON public."leave_balances" USING ((company_id = ( SELECT get_my_company_id() ))) WITH CHECK ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "leave_promotion_notices_company" ON public."leave_promotion_notices" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "leave_requests_delete" ON public."leave_requests" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "leave_requests_insert" ON public."leave_requests" WITH CHECK ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "leave_requests_select" ON public."leave_requests" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "leave_requests_update" ON public."leave_requests" USING ((company_id = ( SELECT get_my_company_id() ))) WITH CHECK ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "via_loan" ON public."loan_payments" USING ((loan_id IN ( SELECT loans.id FROM loans WHERE (loans.company_id IN ( SELECT users.company_id FROM users WHERE (users.id = ( SELECT auth.uid() )))))));
ALTER POLICY "company_isolation" ON public."loans" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "company_access" ON public."monthly_financials" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "company can read own notification settings" ON public."notification_settings" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "company can upsert own notification settings" ON public."notification_settings" USING ((company_id = ( SELECT get_my_company_id() ))) WITH CHECK ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "notifications_delete" ON public."notifications" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "notifications_insert" ON public."notifications" WITH CHECK ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "notifications_select" ON public."notifications" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "notifications_update" ON public."notifications" USING ((company_id = ( SELECT get_my_company_id() ))) WITH CHECK ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "onboarding_admin" ON public."onboarding_checklist_items" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "onboarding_self" ON public."onboarding_checklist_items" USING ((employee_id IN ( SELECT employees.id FROM employees WHERE (employees.user_id = ( SELECT auth.uid() )))));
ALTER POLICY "overtime_requests_delete" ON public."overtime_requests" USING (((company_id = ( SELECT get_my_company_id() )) AND is_company_admin()));
ALTER POLICY "overtime_requests_insert" ON public."overtime_requests" WITH CHECK (((company_id = ( SELECT get_my_company_id() )) AND (employee_id = current_app_employee_id()) AND (status = 'pending'::text) AND (approved_by IS NULL) AND (approved_at IS NULL)));
ALTER POLICY "overtime_requests_select" ON public."overtime_requests" USING (((company_id = ( SELECT get_my_company_id() )) AND (is_company_admin() OR (employee_id = current_app_employee_id()))));
ALTER POLICY "overtime_requests_update" ON public."overtime_requests" USING (((company_id = ( SELECT get_my_company_id() )) AND (is_company_admin() OR (employee_id = current_app_employee_id())))) WITH CHECK (((company_id = ( SELECT get_my_company_id() )) AND (is_company_admin() OR ((employee_id = current_app_employee_id()) AND (status = 'cancelled'::text)))));
ALTER POLICY "partner_aliases_company_access" ON public."partner_aliases" USING ((company_id = ( SELECT get_my_company_id() ))) WITH CHECK ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "Users can delete their company communications" ON public."partner_communications" USING ((company_id IN ( SELECT users.company_id FROM users WHERE (users.id = ( SELECT auth.uid() )))));
ALTER POLICY "Users can insert their company communications" ON public."partner_communications" WITH CHECK ((company_id IN ( SELECT users.company_id FROM users WHERE (users.id = ( SELECT auth.uid() )))));
ALTER POLICY "Users can update their company communications" ON public."partner_communications" USING ((company_id IN ( SELECT users.company_id FROM users WHERE (users.id = ( SELECT auth.uid() )))));
ALTER POLICY "Users can view their company communications" ON public."partner_communications" USING ((company_id IN ( SELECT users.company_id FROM users WHERE (users.id = ( SELECT auth.uid() )))));
ALTER POLICY "partner_invitations_company" ON public."partner_invitations" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "partners_company_access" ON public."partners" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "payment_batches_company" ON public."payment_batches" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "Company members can manage payment queue" ON public."payment_queue" USING ((company_id = ( SELECT get_my_company_id() ))) WITH CHECK ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "Company members can view payment queue" ON public."payment_queue" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "payroll_items_company_policy" ON public."payroll_items" USING ((batch_id IN ( SELECT payment_batches.id FROM payment_batches WHERE (payment_batches.company_id = ( SELECT get_my_company_id() )))));
ALTER POLICY "payslip_overrides_company" ON public."payslip_overrides" USING ((company_id = ( SELECT get_my_company_id() ))) WITH CHECK ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "pgm_delete" ON public."permission_group_members" USING ((company_id IN ( SELECT users.company_id FROM users WHERE ((users.id = ( SELECT auth.uid() )) AND (users.role = ANY (ARRAY['owner'::text, 'admin'::text]))))));
ALTER POLICY "pgm_insert" ON public."permission_group_members" WITH CHECK ((company_id IN ( SELECT users.company_id FROM users WHERE ((users.id = ( SELECT auth.uid() )) AND (users.role = ANY (ARRAY['owner'::text, 'admin'::text]))))));
ALTER POLICY "pgm_select" ON public."permission_group_members" USING ((company_id IN ( SELECT users.company_id FROM users WHERE (users.id = ( SELECT auth.uid() )))));
ALTER POLICY "pgp_delete" ON public."permission_group_permissions" USING ((group_id IN ( SELECT permission_groups.id FROM permission_groups WHERE (permission_groups.company_id IN ( SELECT users.company_id FROM users WHERE ((users.id = ( SELECT auth.uid() )) AND (users.role = ANY (ARRAY['owner'::text, 'admin'::text]))))))));
ALTER POLICY "pgp_insert" ON public."permission_group_permissions" WITH CHECK ((group_id IN ( SELECT permission_groups.id FROM permission_groups WHERE (permission_groups.company_id IN ( SELECT users.company_id FROM users WHERE ((users.id = ( SELECT auth.uid() )) AND (users.role = ANY (ARRAY['owner'::text, 'admin'::text]))))))));
ALTER POLICY "pgp_select" ON public."permission_group_permissions" USING ((group_id IN ( SELECT permission_groups.id FROM permission_groups WHERE (permission_groups.company_id IN ( SELECT users.company_id FROM users WHERE (users.id = ( SELECT auth.uid() )))))));
ALTER POLICY "pg_delete" ON public."permission_groups" USING (((company_id IN ( SELECT users.company_id FROM users WHERE ((users.id = ( SELECT auth.uid() )) AND (users.role = ANY (ARRAY['owner'::text, 'admin'::text]))))) AND (is_system = false)));
ALTER POLICY "pg_insert" ON public."permission_groups" WITH CHECK ((company_id IN ( SELECT users.company_id FROM users WHERE ((users.id = ( SELECT auth.uid() )) AND (users.role = ANY (ARRAY['owner'::text, 'admin'::text]))))));
ALTER POLICY "pg_select" ON public."permission_groups" USING ((company_id IN ( SELECT users.company_id FROM users WHERE (users.id = ( SELECT auth.uid() )))));
ALTER POLICY "pg_update" ON public."permission_groups" USING ((company_id IN ( SELECT users.company_id FROM users WHERE ((users.id = ( SELECT auth.uid() )) AND (users.role = ANY (ARRAY['owner'::text, 'admin'::text]))))));
ALTER POLICY "programs_company_access" ON public."programs" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "quote_approvals_company" ON public."quote_approvals" USING ((company_id = ( SELECT get_my_company_id() ))) WITH CHECK ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "Users can delete own company quote tracking" ON public."quote_tracking" USING ((company_id = ( SELECT users.company_id FROM users WHERE (users.auth_id = ( SELECT auth.uid() )))));
ALTER POLICY "Users can insert own company quote tracking" ON public."quote_tracking" WITH CHECK ((company_id IN ( SELECT employees.company_id FROM employees WHERE (employees.id = ( SELECT auth.uid() )))));
ALTER POLICY "Users can update own company quote tracking" ON public."quote_tracking" USING ((company_id IN ( SELECT employees.company_id FROM employees WHERE (employees.id = ( SELECT auth.uid() )))));
ALTER POLICY "Users can view own company quote tracking" ON public."quote_tracking" USING ((company_id IN ( SELECT employees.company_id FROM employees WHERE (employees.id = ( SELECT auth.uid() )))));
ALTER POLICY "recurring_payments_company" ON public."recurring_payments" USING ((company_id = ( SELECT get_my_company_id() ))) WITH CHECK ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "Owners can manage referral codes" ON public."referral_codes" USING ((company_id IN ( SELECT users.company_id FROM users WHERE ((users.auth_id = ( SELECT auth.uid() )) AND (users.role = ANY (ARRAY['owner'::text, 'admin'::text]))))));
ALTER POLICY "Users can read own referral codes" ON public."referral_codes" USING ((company_id IN ( SELECT users.company_id FROM users WHERE (users.auth_id = ( SELECT auth.uid() )))));
ALTER POLICY "Company members can manage routing rules" ON public."routing_rules" USING ((company_id = ( SELECT get_my_company_id() ))) WITH CHECK ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "Company members can view routing rules" ON public."routing_rules" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "salary_history_company" ON public."salary_history" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "salary_history_policy" ON public."salary_history" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "manage own events" ON public."schedule_events" USING (((company_id = ( SELECT get_my_company_id() )) AND (user_id = ( SELECT users.id FROM users WHERE (users.auth_id = ( SELECT auth.uid() )))))) WITH CHECK (((company_id = ( SELECT get_my_company_id() )) AND (user_id = ( SELECT users.id FROM users WHERE (users.auth_id = ( SELECT auth.uid() ))))));
ALTER POLICY "view shared or own events" ON public."schedule_events" USING (((company_id = ( SELECT get_my_company_id() )) AND ((is_shared = true) OR (user_id = ( SELECT users.id FROM users WHERE (users.auth_id = ( SELECT auth.uid() )))))));
ALTER POLICY "manage own todos" ON public."schedule_todos" USING ((user_id = ( SELECT users.id FROM users WHERE (users.auth_id = ( SELECT auth.uid() ))))) WITH CHECK (((user_id = ( SELECT users.id FROM users WHERE (users.auth_id = ( SELECT auth.uid() )))) AND (company_id = ( SELECT get_my_company_id() ))));
ALTER POLICY "signature_requests_delete" ON public."signature_requests" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "signature_requests_insert" ON public."signature_requests" WITH CHECK ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "signature_requests_select" ON public."signature_requests" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "signature_requests_update" ON public."signature_requests" USING ((company_id = ( SELECT get_my_company_id() ))) WITH CHECK ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "ssf_insert_company" ON public."signature_send_failures" WITH CHECK ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "ssf_select_company_admin" ON public."signature_send_failures" USING (((company_id = ( SELECT get_my_company_id() )) AND is_company_admin()));
ALTER POLICY "ssf_update_company_admin" ON public."signature_send_failures" USING (((company_id = ( SELECT get_my_company_id() )) AND is_company_admin())) WITH CHECK (((company_id = ( SELECT get_my_company_id() )) AND is_company_admin()));
ALTER POLICY "Company members can manage sub deals" ON public."sub_deals" USING ((EXISTS ( SELECT 1 FROM deals d WHERE ((d.id = sub_deals.parent_deal_id) AND (d.company_id = ( SELECT get_my_company_id() )))))) WITH CHECK ((EXISTS ( SELECT 1 FROM deals d WHERE ((d.id = sub_deals.parent_deal_id) AND (d.company_id = ( SELECT get_my_company_id() ))))));
ALTER POLICY "Company members can view sub deals" ON public."sub_deals" USING ((EXISTS ( SELECT 1 FROM deals d WHERE ((d.id = sub_deals.parent_deal_id) AND (d.company_id = ( SELECT get_my_company_id() ))))));
ALTER POLICY "Owners can insert subscription" ON public."subscriptions" WITH CHECK ((company_id IN ( SELECT users.company_id FROM users WHERE ((users.auth_id = ( SELECT auth.uid() )) AND (users.role = ANY (ARRAY['owner'::text, 'admin'::text]))))));
ALTER POLICY "Owners can manage subscription" ON public."subscriptions" USING ((company_id IN ( SELECT users.company_id FROM users WHERE ((users.auth_id = ( SELECT auth.uid() )) AND (users.role = ANY (ARRAY['owner'::text, 'admin'::text]))))));
ALTER POLICY "Users can read own company subscription" ON public."subscriptions" USING ((company_id IN ( SELECT users.company_id FROM users WHERE (users.auth_id = ( SELECT auth.uid() )))));
ALTER POLICY "sync_jobs_company" ON public."sync_jobs" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "Users can view own company sync logs" ON public."sync_logs" USING ((company_id IN ( SELECT users.company_id FROM users WHERE (users.auth_id = ( SELECT auth.uid() )))));
ALTER POLICY "Company members can delete queue" ON public."tax_invoice_queue" USING ((company_id = ( SELECT users.company_id FROM users WHERE (users.auth_id = ( SELECT auth.uid() )))));
ALTER POLICY "Company members can update queue" ON public."tax_invoice_queue" USING ((company_id IN ( SELECT users.company_id FROM users WHERE (users.id = ( SELECT auth.uid() )))));
ALTER POLICY "Company members can view queue" ON public."tax_invoice_queue" USING ((company_id IN ( SELECT users.company_id FROM users WHERE (users.id = ( SELECT auth.uid() )))));
ALTER POLICY "Company members can manage tax invoices" ON public."tax_invoices" USING ((company_id = ( SELECT get_my_company_id() ))) WITH CHECK ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "Company members can view tax invoices" ON public."tax_invoices" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "Company can manage matches" ON public."transaction_matches" USING ((EXISTS ( SELECT 1 FROM transactions t WHERE ((t.id = transaction_matches.transaction_id) AND (t.company_id = ( SELECT get_my_company_id() ))))));
ALTER POLICY "Company can manage transactions" ON public."transactions" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "treasury_positions_company" ON public."treasury_positions" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "treasury_transactions_company" ON public."treasury_transactions" USING ((position_id IN ( SELECT treasury_positions.id FROM treasury_positions WHERE (treasury_positions.company_id = ( SELECT get_my_company_id() )))));
ALTER POLICY "tx_category_options_company" ON public."tx_category_options" USING ((company_id = ( SELECT get_my_company_id() ))) WITH CHECK ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "up_delete" ON public."user_preferences" USING ((user_id = ( SELECT auth.uid() )));
ALTER POLICY "up_insert" ON public."user_preferences" WITH CHECK ((user_id = ( SELECT auth.uid() )));
ALTER POLICY "up_select" ON public."user_preferences" USING ((user_id = ( SELECT auth.uid() )));
ALTER POLICY "up_update" ON public."user_preferences" USING ((user_id = ( SELECT auth.uid() )));
ALTER POLICY "Owners can delete users" ON public."users" USING (((company_id = ( SELECT get_my_company_id() )) AND is_company_owner()));
ALTER POLICY "Users can insert self" ON public."users" WITH CHECK ((auth_id = ( SELECT auth.uid() )));
ALTER POLICY "Users can update" ON public."users" USING (((auth_id = ( SELECT auth.uid() )) OR ((company_id = ( SELECT get_my_company_id() )) AND is_company_owner())));
ALTER POLICY "Users can view company members" ON public."users" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "vault_accounts_company" ON public."vault_accounts" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "vault_assets_company" ON public."vault_assets" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "vault_docs_company" ON public."vault_docs" USING ((company_id = ( SELECT get_my_company_id() )));
ALTER POLICY "Company can manage vendors" ON public."vendors" USING ((company_id = ( SELECT get_my_company_id() )));
