-- 계정과목표를 사장님이 준 표준(계정과목.xlsx)으로 맞춘다 (2026-08-12)
--
--   History: 2026-06-12 시드가 **101 을 보통예금**으로 잡았다. 한국 표준 계정체계는
--     101 현금 · 102 당좌예금 · 103 보통예금 이다. 그 뒤로 전표 엔진(find_account)·
--     vat-voucher.STD.bank·전표입력 화면이 전부 '101 = 통장'을 전제로 쌓였다.
--     2026-08-12 사장님이 표준 엑셀(839행 = 실계정 474 + '회사설정계정과목' 빈칸 365)을 주며
--     "이 리스트로 맞춰라 · 계정과목명에 띄어쓰기는 없이" 지시. 101 을 표준으로 옮기기로 확정.
--
--   ★ 이력 보존의 핵심: journal_lines 는 **account_id** 로 붙어 있다. 그래서 계정 '행'의
--     code 만 바꾸면 그 계정에 달린 전표가 통째로 따라온다. 새로 만들고 옮기는 게 아니다.
--
--   같이 바뀐 것(같은 커밋): post_bank/card/cash/settlement_voucher · generate_voucher_drafts
--     (find_account 가 코드를 우선하므로 '101' 그대로 두면 통장 대신 **현금**을 집는다),
--     src/lib/vat-voucher.ts STD.bank, 전표입력 화면의 code==='101', 안내 문구.
--
--   목록은 src/lib/standard-accounts.ts 와 **같은 원본(엑셀)**에서 뽑았다.
--   다시 뽑을 때는 scripts/gen-standard-accounts.js 를 쓴다.

-- ── 1) 표준 목록을 한 곳에 둔다 ─────────────────────────────────────────────
--   시드와 기존 회사 동기화가 같은 목록을 보게 한다 — 두 벌로 두면 반드시 어긋난다.
CREATE OR REPLACE FUNCTION public.standard_chart_of_accounts()
 RETURNS TABLE (code text, name text, account_type text)
 LANGUAGE sql IMMUTABLE
AS $function$
  VALUES
    ('101', '현금', 'asset'),
    ('102', '당좌예금', 'asset'),
    ('103', '보통예금', 'asset'),
    ('104', '기타제예금', 'asset'),
    ('105', '정기예.적금', 'asset'),
    ('106', '기타단기금융상품', 'asset'),
    ('107', '단기매매증권', 'asset'),
    ('108', '외상매출금', 'asset'),
    ('109', '대손충당금', 'asset'),
    ('110', '받을어음', 'asset'),
    ('111', '대손충당금', 'asset'),
    ('112', '공사미수금', 'asset'),
    ('113', '대손충당금', 'asset'),
    ('114', '단기대여금', 'asset'),
    ('115', '대손충당금', 'asset'),
    ('116', '미수수익', 'asset'),
    ('117', '대손충당금', 'asset'),
    ('118', '분양미수금', 'asset'),
    ('119', '대손충당금', 'asset'),
    ('120', '미수금', 'asset'),
    ('121', '대손충당금', 'asset'),
    ('123', '매도가능증권', 'asset'),
    ('124', '만기보유증권', 'asset'),
    ('131', '선급금', 'asset'),
    ('132', '대손충당금', 'asset'),
    ('133', '선급비용', 'asset'),
    ('134', '가지급금', 'asset'),
    ('135', '부가세대급금', 'asset'),
    ('136', '선납세금', 'asset'),
    ('137', '주.임.종단기채권', 'asset'),
    ('138', '전도금', 'asset'),
    ('139', '선급공사비', 'asset'),
    ('140', '이연법인세자산', 'asset'),
    ('141', '개발비', 'asset'),
    ('146', '상품', 'asset'),
    ('147', '매입환출및에누리', 'asset'),
    ('148', '매입할인', 'asset'),
    ('149', '관세환급금', 'asset'),
    ('150', '제품', 'asset'),
    ('151', '관세환급금', 'asset'),
    ('152', '완성건물', 'asset'),
    ('153', '원재료', 'asset'),
    ('154', '매입환출및에누리', 'asset'),
    ('155', '매입할인', 'asset'),
    ('156', '원재료(도급)', 'asset'),
    ('157', '매입환출및에누리', 'asset'),
    ('158', '매입할인', 'asset'),
    ('159', '원재료(분양)', 'asset'),
    ('160', '매입환출및에누리', 'asset'),
    ('161', '매입할인', 'asset'),
    ('162', '부재료', 'asset'),
    ('163', '매입환출및에누리', 'asset'),
    ('164', '매입할인', 'asset'),
    ('165', '건설용지', 'asset'),
    ('166', '가설재', 'asset'),
    ('167', '저장품', 'asset'),
    ('168', '미착품', 'asset'),
    ('169', '재공품', 'asset'),
    ('170', '미완성공사(도급)', 'asset'),
    ('171', '미완성공사(분양)', 'asset'),
    ('172', '소모품', 'asset'),
    ('176', '장기성예금', 'asset'),
    ('177', '특정현금과예금', 'asset'),
    ('178', '매도가능증권', 'asset'),
    ('179', '장기대여금', 'asset'),
    ('180', '대손충당금', 'asset'),
    ('181', '만기보유증권', 'asset'),
    ('182', '지분법적용투자주식', 'asset'),
    ('187', '투자부동산', 'asset'),
    ('192', '단체퇴직보험예치금', 'asset'),
    ('197', '투자일임계약자산', 'asset'),
    ('198', '퇴직연금운용자산', 'asset'),
    ('199', '퇴직보험예치금', 'asset'),
    ('200', '국민연금전환금', 'asset'),
    ('201', '토지', 'asset'),
    ('202', '건물', 'asset'),
    ('203', '감가상각누계액', 'asset'),
    ('204', '구축물', 'asset'),
    ('205', '감가상각누계액', 'asset'),
    ('206', '기계장치', 'asset'),
    ('207', '감가상각누계액', 'asset'),
    ('208', '차량운반구', 'asset'),
    ('209', '감가상각누계액', 'asset'),
    ('210', '공구와기구', 'asset'),
    ('211', '감가상각누계액', 'asset'),
    ('212', '비품', 'asset'),
    ('213', '감가상각누계액', 'asset'),
    ('214', '건설중인자산', 'asset'),
    ('215', '미착기계', 'asset'),
    ('216', '감가상각누계액', 'asset'),
    ('217', '건설용장비', 'asset'),
    ('218', '감가상각누계액', 'asset'),
    ('219', '시설투자', 'asset'),
    ('220', '감가상각누계액', 'asset'),
    ('222', '감가상각누계액', 'asset'),
    ('224', '감가상각누계액', 'asset'),
    ('226', '감가상각누계액', 'asset'),
    ('228', '감가상각누계액', 'asset'),
    ('230', '감가상각누계액', 'asset'),
    ('231', '영업권', 'asset'),
    ('232', '특허권', 'asset'),
    ('233', '상표권', 'asset'),
    ('234', '실용신안권', 'asset'),
    ('235', '의장권', 'asset'),
    ('236', '면허권', 'asset'),
    ('237', '광업권', 'asset'),
    ('238', '창업비', 'asset'),
    ('239', '개발비', 'asset'),
    ('240', '소프트웨어', 'asset'),
    ('251', '외상매입금', 'liability'),
    ('252', '지급어음', 'liability'),
    ('253', '미지급금', 'liability'),
    ('254', '예수금', 'liability'),
    ('255', '부가세예수금', 'liability'),
    ('256', '당좌차월', 'liability'),
    ('257', '가수금', 'liability'),
    ('258', '예수보증금', 'liability'),
    ('259', '선수금', 'liability'),
    ('260', '단기차입금', 'liability'),
    ('261', '미지급세금', 'liability'),
    ('262', '미지급비용', 'liability'),
    ('263', '선수수익', 'liability'),
    ('264', '유동성장기부채', 'liability'),
    ('265', '미지급배당금', 'liability'),
    ('266', '지급보증채무', 'liability'),
    ('267', '수출금융', 'liability'),
    ('268', '수입금융', 'liability'),
    ('269', '공사손실충당금', 'liability'),
    ('270', '하자보수충당금', 'liability'),
    ('271', '공사선수금', 'liability'),
    ('272', '분양선수금', 'liability'),
    ('273', '이연법인세부채', 'liability'),
    ('291', '사채', 'liability'),
    ('292', '사채할인발행차금', 'liability'),
    ('293', '장기차입금', 'liability'),
    ('294', '임대보증금', 'liability'),
    ('295', '퇴직급여충당부채', 'liability'),
    ('296', '퇴직보험충당부채', 'liability'),
    ('297', '장기미지급금', 'liability'),
    ('298', '중소기업투자준비금', 'liability'),
    ('299', '기술개발준비금', 'liability'),
    ('300', '해외시장개척준비금', 'liability'),
    ('301', '지방이전준비금', 'liability'),
    ('302', '수출손실준비금', 'liability'),
    ('303', '주.임.종장기차입금', 'liability'),
    ('304', '관계회사장기차입금', 'liability'),
    ('305', '외화장기차입금', 'liability'),
    ('306', '장기공사선수금', 'liability'),
    ('307', '장기임대보증금', 'liability'),
    ('308', '장기성지급어음', 'liability'),
    ('309', '환율조정대', 'liability'),
    ('310', '이연법인세부채', 'liability'),
    ('311', '신주인수권부사채', 'liability'),
    ('312', '전환사채', 'liability'),
    ('313', '사채할증발행차금', 'liability'),
    ('314', '장기제품보증부채', 'liability'),
    ('329', '퇴직연금충당부채', 'liability'),
    ('330', '퇴직연금미지급금', 'liability'),
    ('331', '자본금', 'equity'),
    ('332', '우선주자본금', 'equity'),
    ('337', '출자금', 'equity'),
    ('338', '인출금', 'equity'),
    ('341', '주식발행초과금', 'equity'),
    ('342', '감자차익', 'equity'),
    ('343', '자기주식처분이익', 'equity'),
    ('344', '전환권대가', 'equity'),
    ('345', '신주인수권대가', 'equity'),
    ('349', '기타자본잉여금', 'equity'),
    ('350', '재평가적립금', 'equity'),
    ('351', '이익준비금', 'equity'),
    ('352', '기업합리화적립금', 'equity'),
    ('353', '법정적립금임의설정', 'equity'),
    ('354', '재무구조개선적립금', 'equity'),
    ('355', '임의적립금', 'equity'),
    ('356', '사업확장적립금', 'equity'),
    ('357', '감채적립금', 'equity'),
    ('358', '배당평균적립금', 'equity'),
    ('359', '주식할인발행차상각', 'equity'),
    ('360', '배당건설이자상각', 'equity'),
    ('361', '상환주식의상환액', 'equity'),
    ('363', '중소기업투자준비금', 'equity'),
    ('364', '기술개발준비금', 'equity'),
    ('365', '해외시장개척준비금', 'equity'),
    ('366', '지방이전준비금', 'equity'),
    ('367', '수출손실준비금', 'equity'),
    ('368', '기타임의적립금', 'equity'),
    ('369', '회계변경의누적효과', 'equity'),
    ('370', '전기오류수정이익', 'equity'),
    ('371', '전기오류수정손실', 'equity'),
    ('372', '중간배당금', 'equity'),
    ('374', '기타이익잉여금', 'equity'),
    ('375', '이월이익잉여금', 'equity'),
    ('376', '이월결손금', 'equity'),
    ('377', '미처분이익잉여금', 'equity'),
    ('378', '미처리결손금', 'equity'),
    ('379', '당기순이익', 'equity'),
    ('380', '당기순손실', 'equity'),
    ('381', '주식할인발행차금', 'equity'),
    ('382', '배당건설이자', 'equity'),
    ('383', '자기주식', 'equity'),
    ('386', '신주발행비', 'equity'),
    ('387', '미교부주식배당금', 'equity'),
    ('388', '신주청약증거금', 'equity'),
    ('392', '국고보조금', 'equity'),
    ('393', '공사부담금', 'equity'),
    ('394', '감자차손', 'equity'),
    ('395', '자기주식처분손실', 'equity'),
    ('396', '주식매입선택권', 'equity'),
    ('400', '손익', 'equity'),
    ('401', '상품매출', 'revenue'),
    ('402', '매출환입및에누리', 'revenue'),
    ('403', '매출할인', 'revenue'),
    ('404', '제품매출', 'revenue'),
    ('405', '매출환입및에누리', 'revenue'),
    ('406', '매출할인', 'revenue'),
    ('407', '공사수입금', 'revenue'),
    ('408', '매출할인', 'revenue'),
    ('409', '완성건물매출', 'revenue'),
    ('410', '매출할인', 'revenue'),
    ('411', '임대료수입', 'revenue'),
    ('451', '상품매출원가', 'expense'),
    ('452', '도급공사매출원가', 'expense'),
    ('453', '분양공사매출원가', 'expense'),
    ('454', '제조', 'expense'),
    ('455', '제품매출원가', 'expense'),
    ('456', '분양제조', 'expense'),
    ('501', '원재료비', 'expense'),
    ('502', '부재료비', 'expense'),
    ('503', '급여', 'expense'),
    ('504', '임금', 'expense'),
    ('505', '상여금', 'expense'),
    ('506', '제수당', 'expense'),
    ('507', '잡급', 'expense'),
    ('508', '퇴직급여', 'expense'),
    ('509', '퇴직보험충당금전입', 'expense'),
    ('510', '퇴직급여', 'expense'),
    ('511', '복리후생비', 'expense'),
    ('512', '여비교통비', 'expense'),
    ('513', '접대비(기업업무추진비)', 'expense'),
    ('514', '통신비', 'expense'),
    ('515', '가스수도료', 'expense'),
    ('516', '전력비', 'expense'),
    ('517', '세금과공과금', 'expense'),
    ('518', '감가상각비', 'expense'),
    ('519', '지급임차료', 'expense'),
    ('520', '수선비', 'expense'),
    ('521', '보험료', 'expense'),
    ('522', '차량유지비', 'expense'),
    ('523', '경상연구개발비', 'expense'),
    ('524', '운반비', 'expense'),
    ('525', '교육훈련비', 'expense'),
    ('526', '도서인쇄비', 'expense'),
    ('527', '회의비', 'expense'),
    ('528', '포장비', 'expense'),
    ('529', '사무용품비', 'expense'),
    ('530', '소모품비', 'expense'),
    ('531', '지급수수료', 'expense'),
    ('532', '보관료', 'expense'),
    ('533', '외주가공비', 'expense'),
    ('534', '시험비', 'expense'),
    ('535', '기밀비', 'expense'),
    ('536', '잡비', 'expense'),
    ('549', '명예퇴직금', 'expense'),
    ('601', '원재료비', 'expense'),
    ('602', '외주비', 'expense'),
    ('603', '급여', 'expense'),
    ('604', '임금', 'expense'),
    ('605', '상여금', 'expense'),
    ('606', '제수당', 'expense'),
    ('607', '퇴직급여', 'expense'),
    ('608', '퇴직보험충당금전입', 'expense'),
    ('609', '퇴직급여', 'expense'),
    ('610', '중기및운반비', 'expense'),
    ('611', '복리후생비', 'expense'),
    ('612', '여비교통비', 'expense'),
    ('613', '접대비(기업업무추진비)', 'expense'),
    ('614', '통신비', 'expense'),
    ('615', '가스수도료', 'expense'),
    ('616', '전력비', 'expense'),
    ('617', '세금과공과금', 'expense'),
    ('618', '감가상각비', 'expense'),
    ('619', '지급임차료', 'expense'),
    ('620', '수선비', 'expense'),
    ('621', '보험료', 'expense'),
    ('622', '차량유지비', 'expense'),
    ('623', '운반비', 'expense'),
    ('624', '잡자재대', 'expense'),
    ('625', '교육훈련비', 'expense'),
    ('626', '도서인쇄비', 'expense'),
    ('627', '하자보수비', 'expense'),
    ('628', '포장비', 'expense'),
    ('629', '사무용품비', 'expense'),
    ('630', '소모품비', 'expense'),
    ('631', '지급수수료', 'expense'),
    ('632', '보관료', 'expense'),
    ('633', '외주가공비', 'expense'),
    ('634', '장비사용료', 'expense'),
    ('635', '설계용역비', 'expense'),
    ('636', '광고선전비', 'expense'),
    ('637', '소모공구비', 'expense'),
    ('638', '외주공사비', 'expense'),
    ('639', '협회비', 'expense'),
    ('640', '잡비', 'expense'),
    ('641', '공사손실충당금전입', 'expense'),
    ('642', '공사손실충당금환입', 'expense'),
    ('649', '명예퇴직금', 'expense'),
    ('701', '원재료비', 'expense'),
    ('702', '중기및운반비', 'expense'),
    ('703', '급여', 'expense'),
    ('704', '임금', 'expense'),
    ('705', '상여금', 'expense'),
    ('706', '제수당', 'expense'),
    ('707', '퇴직급여', 'expense'),
    ('708', '퇴직보험충당금전입', 'expense'),
    ('709', '퇴직급여', 'expense'),
    ('710', '건설용지비', 'expense'),
    ('711', '복리후생비', 'expense'),
    ('712', '여비교통비', 'expense'),
    ('713', '접대비(기업업무추진비)', 'expense'),
    ('714', '통신비', 'expense'),
    ('715', '가스수도료', 'expense'),
    ('716', '전력비', 'expense'),
    ('717', '세금과공과금', 'expense'),
    ('718', '감가상각비', 'expense'),
    ('719', '지급임차료', 'expense'),
    ('720', '수선비', 'expense'),
    ('721', '보험료', 'expense'),
    ('722', '차량유지비', 'expense'),
    ('723', '경상연구개발비', 'expense'),
    ('724', '잡자재대', 'expense'),
    ('725', '교육훈련비', 'expense'),
    ('726', '도서인쇄비', 'expense'),
    ('727', '회의비', 'expense'),
    ('728', '포장비', 'expense'),
    ('729', '사무용품비', 'expense'),
    ('730', '소모품비', 'expense'),
    ('731', '지급수수료', 'expense'),
    ('732', '보관료', 'expense'),
    ('733', '외주가공비', 'expense'),
    ('734', '시험비', 'expense'),
    ('735', '설계용역비', 'expense'),
    ('736', '가설재손료', 'expense'),
    ('737', '잡비', 'expense'),
    ('741', '공사손실충당금전입', 'expense'),
    ('742', '공사손실충당금환입', 'expense'),
    ('743', '외주비', 'expense'),
    ('749', '명예퇴직금', 'expense'),
    ('801', '임원급여', 'expense'),
    ('802', '직원급여', 'expense'),
    ('803', '상여금', 'expense'),
    ('804', '제수당', 'expense'),
    ('805', '잡급', 'expense'),
    ('806', '퇴직급여', 'expense'),
    ('807', '퇴직보험충당금전입', 'expense'),
    ('808', '퇴직급여', 'expense'),
    ('811', '복리후생비', 'expense'),
    ('812', '여비교통비', 'expense'),
    ('813', '접대비(기업업무추진비)', 'expense'),
    ('814', '통신비', 'expense'),
    ('815', '수도광열비', 'expense'),
    ('816', '전력비', 'expense'),
    ('817', '세금과공과금', 'expense'),
    ('818', '감가상각비', 'expense'),
    ('819', '지급임차료', 'expense'),
    ('820', '수선비', 'expense'),
    ('821', '보험료', 'expense'),
    ('822', '차량유지비', 'expense'),
    ('823', '경상연구개발비', 'expense'),
    ('824', '운반비', 'expense'),
    ('825', '교육훈련비', 'expense'),
    ('826', '도서인쇄비', 'expense'),
    ('827', '회의비', 'expense'),
    ('828', '포장비', 'expense'),
    ('829', '사무용품비', 'expense'),
    ('830', '소모품비', 'expense'),
    ('831', '지급수수료', 'expense'),
    ('832', '보관료', 'expense'),
    ('833', '광고선전비', 'expense'),
    ('834', '판매촉진비', 'expense'),
    ('835', '대손상각비', 'expense'),
    ('836', '기밀비', 'expense'),
    ('837', '건물관리비', 'expense'),
    ('838', '수출제비용', 'expense'),
    ('839', '판매수수료', 'expense'),
    ('840', '무형고정자산상각', 'expense'),
    ('841', '환가료', 'expense'),
    ('842', '견본비', 'expense'),
    ('843', '해외접대비(기업업무추진비)', 'expense'),
    ('844', '해외시장개척비', 'expense'),
    ('845', '미분양주택관리비', 'expense'),
    ('846', '수주비', 'expense'),
    ('847', '하자보수충당금전입', 'expense'),
    ('848', '잡비', 'expense'),
    ('849', '명예퇴직금', 'expense'),
    ('850', '대손충당금환입', 'expense'),
    ('851', '퇴직급여충당부채환입', 'expense'),
    ('852', '제작비', 'expense'),
    ('853', '여비교통비(출장비)', 'expense'),
    ('854', '지급수수료(위임)', 'expense'),
    ('901', '이자수익', 'revenue'),
    ('902', '만기보유증권이자', 'revenue'),
    ('903', '배당금수익', 'revenue'),
    ('904', '수입임대료', 'revenue'),
    ('905', '단기투자자산평가익', 'revenue'),
    ('906', '단기투자자산처분익', 'revenue'),
    ('907', '외환차익', 'revenue'),
    ('908', '법인세환급액', 'revenue'),
    ('909', '수입수수료', 'revenue'),
    ('910', '외화환산이익', 'revenue'),
    ('911', '사채상환이익', 'revenue'),
    ('912', '전기오류수정이익', 'revenue'),
    ('913', '하자보수충당금환입', 'revenue'),
    ('914', '유형자산처분이익', 'revenue'),
    ('915', '투자자산처분이익', 'revenue'),
    ('916', '상각채권추심이익', 'revenue'),
    ('917', '자산수증이익', 'revenue'),
    ('918', '채무면제이익', 'revenue'),
    ('919', '보험차익', 'revenue'),
    ('920', '투자증권손상차환입', 'revenue'),
    ('921', '지분법이익', 'revenue'),
    ('922', '만기보유증권처분이익', 'revenue'),
    ('930', '잡이익', 'revenue'),
    ('931', '이자비용', 'expense'),
    ('932', '외환차손', 'expense'),
    ('933', '기부금', 'expense'),
    ('934', '기타의대손상각비', 'expense'),
    ('935', '외화환산손실', 'expense'),
    ('936', '매출채권처분손실', 'expense'),
    ('937', '단기투자자산평가손', 'expense'),
    ('938', '단기투자자산처분손', 'expense'),
    ('939', '재고자산감모손실', 'expense'),
    ('940', '재고자산평가손실', 'expense'),
    ('941', '재해손실', 'expense'),
    ('942', '전기오류수정손실', 'expense'),
    ('943', '투자증권손상차손', 'expense'),
    ('944', '지분법손실', 'expense'),
    ('947', '회사채이자', 'expense'),
    ('948', '사채상환손실', 'expense'),
    ('949', '보상비', 'expense'),
    ('950', '유형자산처분손실', 'expense'),
    ('951', '투자자산처분손실', 'expense'),
    ('952', '유형자산폐기손실', 'expense'),
    ('957', '특별상각', 'expense'),
    ('960', '잡손실', 'expense'),
    ('961', '이연법인세자산', 'asset'),
    ('962', '임차보증금', 'asset'),
    ('963', '전세권', 'asset'),
    ('964', '기타보증금', 'asset'),
    ('965', '장기외상매출금', 'asset'),
    ('966', '현재가치할인차금', 'asset'),
    ('967', '대손충당금', 'asset'),
    ('968', '장기받을어음', 'asset'),
    ('969', '현재가치할인차금', 'asset'),
    ('970', '대손충당금', 'asset'),
    ('971', '장기미수금', 'asset'),
    ('972', '현재가치할인차금', 'asset'),
    ('973', '대손충당금', 'asset'),
    ('974', '장기선급비용', 'asset'),
    ('975', '장기선급금', 'asset'),
    ('976', '부도어음과수표', 'asset'),
    ('977', '대손충당금', 'asset'),
    ('978', '전신전화가입권', 'asset'),
    ('981', '매도가능증권평가익', 'equity'),
    ('982', '매도가능증권평가손', 'equity'),
    ('983', '해외사업환산이익', 'equity'),
    ('984', '해외사업환산손실', 'equity'),
    ('985', '파생상품평가이익', 'equity'),
    ('986', '파생상품평가손실', 'equity'),
    ('991', '사업중단직접비', 'expense'),
    ('992', '중단사업자산손상차', 'expense'),
    ('993', '중단사업손상차환입', 'revenue'),
    ('997', '중단손익', 'expense'),
    ('998', '법인세등', 'expense'),
    ('999', '소득세등', 'expense')
$function$;

COMMENT ON FUNCTION public.standard_chart_of_accounts() IS
  '표준 계정과목 474개 (사장님 제공 계정과목.xlsx, 2026-08-12). 계정과목명에 띄어쓰기 없음. src/lib/standard-accounts.ts 와 같은 원본.';

-- ── 2) 전표 엔진: 보통예금 101 → 103 ────────────────────────────────────────
--   본문을 다시 쓰지 않고 정의를 읽어 코드만 치환한다 — 손으로 옮기다 생기는 오타를 막는다.
DO $$
DECLARE r record;
BEGIN
  FOR r IN
    SELECT pg_get_functiondef(p.oid) AS def
    FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public' AND p.prokind = 'f'
      AND p.proname IN ('generate_voucher_drafts', 'post_bank_voucher',
                        'post_card_voucher', 'post_cash_voucher', 'post_settlement_voucher')
      AND pg_get_functiondef(p.oid) LIKE '%''101''%'
  LOOP
    EXECUTE replace(r.def, '''101''', '''103''');
  END LOOP;
END $$;

-- ── 3) 기존 회사 계정과목표를 표준으로 ──────────────────────────────────────
--   3-1. 쓰이고 있는 계정은 **행을 옮긴다**(코드만 변경 → 전표 이력 유지).
--        옮길 자리(103·930·960)는 지금 시드에 없어 비어 있다.
UPDATE public.chart_of_accounts SET code = '103' WHERE code = '101' AND name = '보통예금';
UPDATE public.chart_of_accounts SET code = '930' WHERE code = '901' AND name = '잡이익';
UPDATE public.chart_of_accounts SET code = '960' WHERE code = '980' AND name = '잡손실';

--   3-2. 표준에 없는 자리 정리 — 100 현금. 표준은 101 이 현금이다.
--        어디에도 안 쓰인 것만 지운다(전표·카드매핑·전표규칙·부모계정 전부 확인).
DELETE FROM public.chart_of_accounts a
WHERE a.code = '100' AND a.name = '현금'
  AND NOT EXISTS (SELECT 1 FROM public.journal_lines l WHERE l.account_id = a.id)
  AND NOT EXISTS (SELECT 1 FROM public.card_account_mappings m WHERE m.account_id = a.id)
  AND NOT EXISTS (SELECT 1 FROM public.voucher_account_rules v WHERE v.account_id = a.id)
  AND NOT EXISTS (SELECT 1 FROM public.chart_of_accounts c WHERE c.parent_id = a.id);

--   3-3. 표준 474개를 모든 회사에 맞춘다 — 있으면 이름·성격 갱신, 없으면 추가.
--        is_system 은 건드리지 않는다(엔진이 물고 있다는 표시라 옮겨온 행의 값을 지켜야 한다).
INSERT INTO public.chart_of_accounts (company_id, code, name, account_type)
SELECT t.company_id, s.code, s.name, s.account_type
FROM (SELECT DISTINCT company_id FROM public.chart_of_accounts) t
CROSS JOIN public.standard_chart_of_accounts() s
ON CONFLICT (company_id, code) DO UPDATE
  SET name = EXCLUDED.name, account_type = EXCLUDED.account_type;

-- ── 4) 신규 회사 시드도 같은 목록을 쓴다 ───────────────────────────────────
CREATE OR REPLACE FUNCTION public._seed_chart_of_accounts_internal(p_company_id uuid)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_count int := 0;
BEGIN
  IF p_company_id IS NULL THEN RETURN 0; END IF;
  IF EXISTS (SELECT 1 FROM public.chart_of_accounts WHERE company_id = p_company_id) THEN
    RETURN 0;
  END IF;

  --   is_system = 전표 엔진이 코드로 직접 찾는 계정. 사람이 지우면 자동분개가 멈춘다.
  INSERT INTO public.chart_of_accounts (company_id, code, name, account_type, is_system)
  SELECT p_company_id, s.code, s.name, s.account_type,
         s.code = ANY (ARRAY['103','108','135','136','251','253','255','401','404','831'])
  FROM public.standard_chart_of_accounts() s
  ON CONFLICT (company_id, code) DO NOTHING;

  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$function$;

-- ── 5) 표준의 '회사설정계정과목'(빈칸) 자리에 남아 있던 옛 시드 3개 정리 ──────
--   122 선급금 · 227 소프트웨어 · 335 자본잉여금.
--   표준은 그 자리를 **빈칸**으로 두므로 3-3 의 upsert 가 덮지 못했다. 그런데 표준에는
--   같은 계정이 제자리에 이미 있다(131 선급금 · 240 소프트웨어 · 349 기타자본잉여금).
--   두 벌로 두면 사람이 둘 중 아무거나 골라 장부가 갈린다. 안 쓰인 것만 지운다.
DELETE FROM public.chart_of_accounts a
WHERE (a.code, a.name) IN (('122','선급금'), ('227','소프트웨어'), ('335','자본잉여금'))
  AND NOT EXISTS (SELECT 1 FROM public.journal_lines l WHERE l.account_id = a.id)
  AND NOT EXISTS (SELECT 1 FROM public.card_account_mappings m WHERE m.account_id = a.id)
  AND NOT EXISTS (SELECT 1 FROM public.voucher_account_rules v WHERE v.account_id = a.id)
  AND NOT EXISTS (SELECT 1 FROM public.chart_of_accounts c WHERE c.parent_id = a.id);
