-- (직접 유입) 중복 집계 수정 (2026-07-29) — prod 에 MCP apply_migration 으로 적용됨.
-- 기존: referrer 없는 page_views 행 기준 집계 — 외부(네이버 등)로 들어온 방문자도
--   내부 페이지 이동분이 전부 리퍼러 없음이라 '(직접 유입)'에 이중 카운트돼 부풀었다.
-- 변경: (직접 유입) = 기간 내 외부 리퍼러가 '한 번도 없는' 방문자만.
--   외부 유입은 호스트별 고유 방문자 그대로. 전문은 apply_migration(동명)과 동일 —
--   platform_traffic_stats 의 top_referrers 서브쿼리만 교체.
